### ISSUE TITLE
Editable Merge Conflict Resolver

### ISSUE THREAD

**Issue by markjerz** [ForkIssues/TrackerWin#101]
When merging conflicts using the in-built merge conflict resolver it would be great to be able to edit the result inside the tool. There's (obviously) often cases where I want a bit of either side or I need to add in an extra `}` but I need to switch to a different tool to finish the job.

**Comment by sm-g** [comment]
> There's (obviously) often cases where I want a bit of either side or I need to add in an extra `}` but I need to switch to a different tool to finish the job.

More often there are cases when built-in resolver could not autoresolve conflicts and third-party tool solved them. Then why spend time to improve built-in?..

**Comment by DanPristupov** [comment]
@sm-g toxicity, huh :)?

Since we are here. Without getting into details, I believe algorithm behind Fork merger is more advanced than in majority of 3rd party mergers. But of course it might handle worse some *particular* cases.

Regarding the editable merge. It's already implemented and we are testing it right now. We had to rewrite the whole merger from scratch and now we want to be sure that everything is OK. I'd expect that feature to appear in Fork in a month or so.

**Comment by sm-g** [comment]
@DanPristupov My point was that you do not need to implement something when there is already tool for that job.

**Comment by DanPristupov** [comment]
The editable merger is available in 1.30 ⭐️
