### ISSUE TITLE
Always pops up the github login dialog

### ISSUE THREAD

**Issue by ykgw-liuxin** [ForkIssues/TrackerWin#1025]
**Problem:**
  The "Connect to GitHub" dialog box pops up every once in a while, and there are a lot of dialog boxes left on your desktop over time. Is there a way to disable it?

**Version:**
  1.55.5.0 windows

![fork-github](https://user-images.githubusercontent.com/66941447/99203240-e43e8600-27ec-11eb-9078-6fce230d11a2.png)

**Comment by DanPristupov** [comment]
Looks like Git Credential Manager (https://github.com/microsoft/Git-Credential-Manager-Core) cannot remember your credentials properly.

Check your remote repository address. Does it contain a username?


<img width="348" alt="Screen Shot 2020-11-16 at 07 50 25" src="https://user-images.githubusercontent.com/618115/99221182-64aaba00-27e0-11eb-8b6d-58c65bf42717.png">

**Comment by ykgw-liuxin** [comment]
thank you for your reply. @DanPristupov 

Yes. my remote repository address contains a username.
Because I use both github and github enterprise and they use different users.
To differentiate, I put username on the remote url.
Is there a way to solve my problem?

**Comment by DanPristupov** [comment]
Interesting, maybe GCM-Core has a bug in the username matching.

I just checked and it looks like username is case sensitive. Could you have a look if you use same capitalization as on the GitHub website?

**Comment by ykgw-liuxin** [comment]
My username is lowercase locally and on GitHub.

But the item previously saved in the Credential Manager disappeared.
I re-entered my password and the item in the Credential Manager came back.
It seems that the dialog box doesn't pop up anymore.

thanks @DanPristupov , I'll close this issue.

**Comment by jarmo** [comment]
I have the same problem after last Fork update (version 1.55.5). Even if I click on the "Sign in with your browser" and see "Authentication Succeeded" message this popup opens up all the time.

@ykgw-liuxin can you describe exactly what did you do so that this proplem disappeared?

@DanPristupov this problem appeared right after Fork got updated to the latest version. I remember that internal Git was also upgraded with that update - maybe it's related?

PS! It seems that popup stopped opening after I changed back to older Git version from Fork Preferences.

**Comment by ykgw-liuxin** [comment]
@jarmo I just
1. close the "Connect to GitHub" dialog.
2. click "Fetch" button, then the fork pops up the password dialog box.
3. input the correct password, the problem disappeared.
