### ISSUE TITLE
Custom-Command branch placeholder contains wrong content

### ISSUE THREAD

**Issue by its-csc** [ForkIssues/TrackerWin#1048]
I want to create a custom-branch-command to open an URL, that contains the branch shortname.
I created a command with the URL parameter: `https://jira.my-company.com/browse/$shortname`

My branchs name is `6.0.0/dev/abc-123`.
The part `abc-123` is a Jira ticket ID.

The configuration should open the URL `https://jira.my-company.com/browse/abc-123`
but it opens `https://jira.my-company.com/browse/6.0.0/dev/abc-123`, with the full branch name.

I thought that the placeholder **$shortname** contains only the last part of the branchname!?

**Comment by DanPristupov** [comment]
`$shortname` exists to differentiate full and short names for remote branches.

For example for `origin/master`:
`$name: origin/master`
`$shortname: master`

> The configuration should open the URL `https://jira.my-company.com/browse/abc-123`
but it opens `https://jira.my-company.com/browse/6.0.0/dev/abc-123`, with the full branch name.

It will work if you name your branches using the Jira ID format (for example: `abc-123`). Otherwise I'm not sure what can be a flexible solution there.

**Comment by its-csc** [comment]
Got it, thanks!
Couldn't find a documentation for these placeholders.

And I found another feature, that helps (Issue Tracker integration with commit-text-links). So I can include the ID in a commit message and click the link in there.

**Comment by DanPristupov** [comment]
> And I found another feature, that helps (Issue Tracker integration with commit-text-links). So I can include the ID in a commit message and click the link in there.

Yes, this is very useful. The Issue Tracker configuration dialog contains a sample for Jira.
