### ISSUE TITLE
[Bug] In commit title, cut is doing copy only

### ISSUE THREAD

**Issue by frankbenoit** [ForkIssues/TrackerWin#1084]
In the commit title, pressing ctrl-x or shift-del does not cut, but a copy of the selected text.

**Comment by DanPristupov** [comment]
Looks like a system glitch.

I just tried, both `Ctrl+x` and `Shift+Del` cut the selected text properly for me.

**Comment by gotoh** [comment]
I am getting same issue in some text inputs like commit subject, commit description, search text, quick launch command.
I found it occurs when using keyhac.exe (key stroke customization tool)
- [Keyhac](https://sites.google.com/site/craftware/keyhac-en)

The fork.exe instance executed after exit the keyhac works fine for ctrl-c and ctrl-Del.
It wonder fork.exe is using low level key operation or using system hook like keyhac.
As far as I know, the fork.exe is the only program having such issue with keyhac.
I hope this issue will be fixed because I'm heavy user of keyhac.

**Comment by DanPristupov** [comment]
> It wonder fork.exe is using low level key operation or using system hook like keyhac.

No, we don't do anything like that. It's just a pretty standard WPF application.

> As far as I know, the fork.exe is the only program having such issue with keyhac.

Nowadays there are not many WPF applications. Probably [ILSpy](https://github.com/icsharpcode/ILSpy/releases/tag/v6.2.1) will also have a similar problem.

**Comment by gotoh** [comment]
Oh, WPF app.
Yeah, I found ILSpy.exe cause the same issue as you guess.
And [ExcelMerge.exe](https://github.com/skanmera/ExcelMerge/blob/master/README.jp.md) also.
So, for my case, it seems the issue comes from incompatibility between WPF and keyhac.
