### ISSUE TITLE
"Fetch remote automatically" will fetch multiple times

### ISSUE THREAD

**Issue by imerr** [ForkIssues/TrackerWin#1154]
When the option is enabled, fork will fetch from upstream in the background
With large changes this may lead to it fetching multiple times at once (I've had it attempt to download a large change set 6 times at once now before I noticed and cancelled it), which obviously shouldn't happen.
It should only try to run one fetch operation per remote at a time

**Comment by DanPristupov** [comment]
Automatic fetch happens every 20 minutes. How large are your changes that fetch takes 20 * 6 = 120 minutes?

**Comment by imerr** [comment]
> 
> 
> Automatic fetch happens every 20 minutes. How large are your changes that fetch takes 20 * 6 = 120 minutes?

Multi-gigabyte ones on a slow-ish network. 

Keep in mind with every additional running fetch it'll get slower and slower as they try to compete for the already limited bandwidth

**Comment by JeReT** [comment]
Probably it should simply not fetch if any other operation is in progress. Instead, it should fetch as soon as that operation is done.
However, I guess this is minor because 99.9% of the users will never run into such an issue.

**Comment by joaosigma** [comment]
Another scenario that falls into this "fetch multiple times" category is when you have two tabs opened and one of them is a worktree of the other one. Since both point to the same repo, just different branches, they actually fetch from the same source and end up updating the same repo.

If a tab is a worktree of a repo already opened in another tab (worktree or not), it should skip the "automatic fetch" on one of them.

**Comment by DanPristupov** [comment]
Actually, starting from 1.81 Fork will not start a new fetch if the old operation is in progress.
