### ISSUE TITLE
[Feature Request] Tab to auto complete branch name suggestions

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#1219]
Currently if you are typing branch directory names and press tab it just focuses the Create button instead of autocompleting the top result.

![image](https://user-images.githubusercontent.com/49417395/123855262-8cb0de80-d8d4-11eb-8087-bb70b8f7b3b3.png)

Not the most annoying thing ever but I'd really like to not have to switch to the mouse to make use of skipping a few letters when I use the feature.

Fork is awesome!

**Comment by jerone** [comment]
Yes please. I was fooled by it a few times. As <kbd>Tab</kbd> has no use in this input field, it would be nice to have it mapped to the autocomplete menu.

**Comment by Otiel** [comment]
But please keep <kbd>Tab</kbd> / <kbd>Shift</kbd><kbd>Tab</kbd> behavior when no autocomplete popup is displayed, as they are basic accessibility keyboard shortcuts to navigate between controls.

I constantly use <kbd>Tab</kbd> on this window to navigate to the "Check out after create" checkbox (since there is no mnemonic #320).

**Comment by DanPristupov** [comment]
We implemented that in 1.64

**Comment by ghost** [comment]
Awesome thanks!
