### ISSUE TITLE
[Feature suggestion] Autocomplete filenames within commit message

### ISSUE THREAD

**Issue by hmrc87** [ForkIssues/TrackerWin#1315]
Hi,
other GIT clients like git-extensions already do it: If you write a commit message and mention a file it gives you autocomplete suggestions. I think this is a nice feature to have - although there should be a switch if users don't want it!

**Comment by hmrc87** [comment]
Is this even considered?

**Comment by DanPristupov** [comment]
We had that functionality in Fork at the beginning, but then removed it, because it only makes sense in `C#` and `Java` where file names match the class names. For the rest of languages it's more distracting than helpful.

**Comment by hmrc87** [comment]
Thank you so much for the explanation which makes sense! but it could be an optional setting :)

**Comment by DanPristupov** [comment]
That's not as easy as it sounds. The problem is, 99% of users never change the default settings.

- if we enable it by default, the majority will not like it
- if we disable it by default, no one will ever find and use it. And why should we implement a quite complex autocomplete feature while no one is going to use it, and then fix and maintain it? We are not a large corporation with a lot of resources.

We give priority and spend our time on other tasks which should improve the application for all users. I mean, I'm not strongly against this feature, but I don't see how to make it work for everyone.

**Comment by hmrc87** [comment]
thank you for the good explanation! I really appreciate your transparency
