### ISSUE TITLE
Pull from another branch doesn't work anymore

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#1383]
Steps to reproduce:
1. update to Fork Version 1.69.3.0
2. create a feature branch from develop and commit / push something to it
2. switch to develop
3. commit / push something to develop
4. switch to the feature branch
5. pull from develop

Result:
I cannot pull anymore
![grafik](https://user-images.githubusercontent.com/530561/142852267-25151ea4-02fc-4bd7-a18e-0c5e09b8a068.png)
I have to open the command window and write
` git config pull.rebase false`
afterwards it works again.

Expected result:
fork should make sure, git is correctly configured after updating and pulling from other branches works out of the box.

**Comment by VincentMarmen** [comment]
I also have been experiencing this issue since updating. From what I can see, it seems related to the Git instance update that was made with Fork 1.69.3. I tried to switch to another Git instance that I have installed on my computer and now it works correctly.

When using the internal Git instance, going into to the Console and typing `git config pull.rebase` will return nothing. However if I use my other instance (which is the same version 2.33.1.windows.1) the same command will return `false`.

**Comment by dougbinks** [comment]
I am also seeing this with 1.69.3 on any pull which requires a merge - i.e. if there is a local commit not on the remote and you pull a changed branch from the remote.

Switching to the system git fixes this.

It thus appears that the fork git instance config has changed.

**Comment by DanPristupov** [comment]
I released the 1.69.4 hotfix which solves that problem
