### ISSUE TITLE
Diff again selected branch?

### ISSUE THREAD

**Issue by xoyojank** [ForkIssues/TrackerWin#1426]
there is a useful feature in SourceTree, which can compare two branches
![image](https://user-images.githubusercontent.com/2873643/148869540-2e0eca81-11d3-4bf0-b2a7-37bb1d4ebe28.png)

**Comment by DanPristupov** [comment]
> there is a useful feature in SourceTree, which can compare two branches

You can compare any two branches (or commits) by selecting them (hold Ctrl for multiselection).

**Comment by JeReT** [comment]
Wow, another hidden feature!
would be great if you could also add a button "view in external diff tool".

**Comment by DanPristupov** [comment]
> Wow, another hidden feature!

It's not that hidden. If I remember correctly, the ability to select multiple commits to diff also exists in ST.

> would be great if you could also add a button "view in external diff tool".

This option is available in file context menu.

**Comment by MilanAssuied** [comment]
Hi, I up this because this feature is no where to be found and is essential.

I can compare my local work folder with a commit, but I need to do this via the tree view, which is unbearable in the repo I am working with. I would like to be able to select two branches from the left pane, and be able to perform a diff on them. If the feature wasn't removed, I can't see it. Is that possible ?

**Comment by DanPristupov** [comment]
> I would like to be able to select two branches from the left pane, and be able to perform a diff on them.

When you select two branches on the sidebar, Fork will show diff for them.


https://github.com/fork-dev/TrackerWin/assets/618115/70ecb01e-6b5b-4fda-89a0-d27fab4b450f
