### ISSUE TITLE
[Feature Request][UI adjustment] Branch color should be the same

### ISSUE THREAD

**Issue by krokofant** [ForkIssues/TrackerWin#1477]
![image](https://user-images.githubusercontent.com/5908498/156766635-f2535c72-3a3d-400f-84eb-ca71beec68dc.png)
It could be a lot easier to see which branch this commit belongs to if the color matched the line on the left.

The brown line and red label belongs to the same branch. But with the context of color you can confused red line with the red label even though they're not related.

**Comment by ZaLiTHkA** [comment]
looking at the partial screen shot there, this feels more like something went awry with the branch colouring. 🤔 in my years using Fork, I've never seen a branch label colour _not_ match it's line in the graph in any of my repos (well over 100 in total).

just to be clear: I don't currently have any _real world_ repositories with that many branches, so I just created one with 8 very simple branches (just to get the lines), and I still don't see this behaviour..

---

with that said, since we can't see where the different branches originated (which I believe is used to pick the branch colours), my simple test now probably missed whatever "branch path" caused this to occur in the first place.

still, this feels more like a "bug report" than a "feature request".

**Comment by krokofant** [comment]
@ZaLiTHkA When looking at this now I can't see the same issue. So maybe it's fixed? At least I can't see it anymore.

Example:
![image](https://user-images.githubusercontent.com/5908498/175255425-147df71b-bc36-4aaf-9ed7-da8af6f6b8ff.png)
