### ISSUE TITLE
Git Vulnerability

### ISSUE THREAD

**Issue by markmonster** [ForkIssues/TrackerWin#1509]
At this moment there's a vulnerability published about Git versions below 2.35.2

https://github.blog/2022-04-12-git-security-vulnerability-announced/

Any plans for an update of the git instance included in Fork?

**Comment by DanPristupov** [comment]
> Any plans for an update of the git instance included in Fork?

No, not yet. The latest release is not stable and I couldn't even make it run on my computer. So, expect another hotfix to be released, at least.

And since we are here, this is what the article says:

> This vulnerability affects users working on multi-user machines where a malicious actor could create a .git directory in a shared location above a victim’s current working directory. 

In other words, you are only affected if the attacker has a physical access to your machine with higher privileges than you. And if the attacker has an access to your machine with higher privileges than you, I guess you have much bigger problem than that vulnerability in git :).

And regarding the hotfix... Well, the fix for that 'vulnerability' is to ask user to agree with opening repos from 'unsafe' places.

**Comment by shtirlic** [comment]
I updated to latest GIT on Windows machine while adding repos as safe dirs helps, some repos are not even opening in Fork while working with windows git bash, see the screenshot

![image](https://user-images.githubusercontent.com/74080/163526489-c8a4f417-3cfd-4a4a-a45d-b86be7a92bff.png)

**Comment by DanPristupov** [comment]
> So, expect another hotfix to be released, at least.

And as I said, another update has been released: https://github.com/git-for-windows/git/releases/tag/v2.35.3.windows.1
