### ISSUE TITLE
[Feature Request] Support for Whitespaces in paths to programs for Custom Commands

### ISSUE THREAD

**Issue by Teeliebhaber** [ForkIssues/TrackerWin#1545]
Hi! 
Yesterday i wanted to add a custom repo command to open a program directly through fork.
On my main working machine this worked fine because the path to the application did not contain whitespaces in directory names.
On my secondary machine however the path was like C:\Users\My Name\...
Because here i have a whitespace in the directory name, my custom command world not work and would open a text file with the path 
C\Users\My.
Is it possible to support those paths as well, or is there already a way to achieve this? 
I tried to wrap the paths with whitespaces in them with double quotation marks but it didnt do the job.

Thanks!

**Comment by DanPristupov** [comment]
I'm sorry, it's been quite a while, but I didn't have time to check it out earlier. Not sure if the problem is still actual.

Everything is working correctly for me. If the target application does not support spaces in parameters, then quotes help.

I tested opening files in Visual Studio using the following configuration.

Doesn't work:
<img width="827" alt="Screenshot 2023-03-29 at 17 22 14" src="https://user-images.githubusercontent.com/618115/228587804-90da5751-79a1-4d58-8f10-0d8eff9576ed.png">

Works:
<img width="827" alt="Screenshot 2023-03-29 at 17 22 48" src="https://user-images.githubusercontent.com/618115/228587980-4427544e-ce26-4603-8b20-ea036ca1d59f.png">
