### ISSUE TITLE
Double click on submodule doesn't activate new tab

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#155]
### Current situation
Every time I double-click to open an submodule, it opens the tab in the background. I have to navigate to the background tab, to be able to open it.

### Expected situation
When I double-click to open an submodule, it gives me focus to that tab, so I instantly can work on it.

**Comment by DanPristupov** [comment]
I confirm this.

- The 'Open Submodule' button in the new `submodule diff` view works properly. And it calls the same code!
- 'Open Submodule in New Tab' context menu item for file in `Changes` view does activate the tab too. However double click on the same item doesn't.

I suppose the problem is caused by double click.

**Comment by jerone** [comment]
I know it used to work correctly, but that was a few version ago.

**Comment by jerone** [comment]
Funny finding; if you double-click with your **right** mouse-button, it works as intended.

**Comment by DanPristupov** [comment]
Good observation :). Seems like we handle the double-click somewhere else.

**Comment by DanPristupov** [comment]
Fixed in 1.30

**Comment by jerone** [comment]
Confirmed working again 🎉
