### ISSUE TITLE
[Feature Request] Ability to discard staged changes

### ISSUE THREAD

**Issue by DamianPatrick** [ForkIssues/TrackerWin#1563]
Hello there,

I switched from SourceTree to Fork because of its superior speed and because it's overall just better. However there's one feature that SourceTree has that would be nice to have in Fork as well and that is the ability to discard staged changes.

See this image:
![image](https://user-images.githubusercontent.com/98882053/174028468-e611ca95-86c0-42aa-b26a-8da6ecbb9de1.png)
Right now there's no "discard" option, hitting DEL also doesn't work.

The reason why I would think it's a nice feature to have is because else I need to first unstage the file which is not always what I want to do because then the staged files would mix with the unstaged files and get lost in clutter. 

As a workaround I now just stash the files which works fine but this is not an ideal solution as it creates clutter in the stash list.

So was hoping we could maybe implement this feature? 🙏 

Cheers

**Comment by DanPristupov** [comment]
`→` means 'depends'

unstaged changes `→` staged changes `→` repository 

Discarding staged changes is dangerous because the unstaged changes are dependent on them. Violating that dependency may lead to accidental data loss.

Steps to reproduce:
1. Make some changes and stage them.
2. Update same lines in the editor
3. Try to discard the staged changes (unstaged changes `→` ~~staged changes~~ `→` repository )
4. Abort
5. Both staged and unstaged changes are lost

Another reason to not allow to discard staged files is that you can't discard a particular chunk in the staged changes. I don't want to introduce a feature which works for files, but not for chunks.

**Comment by DamianPatrick** [comment]
Ah ok. Although I did use this feature in SourceTree fairly often and don't remember ever running into the data loss issue. 
But I do of course understand that it's possible to happen and at the end of the day it's up to you :) 

Thanks for the reply Mr. Pristupov, have a good day.

**Comment by andrewsm80** [comment]
> Discarding staged changes is dangerous because the un-staged changes are dependent on them.
1) The same danger exists when simply un-staging changes: changes that are not staged can be unexpectedly overwritten when other changes are moved from "staged" to "un-staged". 
2) Perhaps the danger could be eliminated by checking for overlap between the staged and un-staged changes, and providing a warning or disabling the operation in case of such overlap. I can imagine that might be difficult though.
>Another reason to not allow to discard staged files is that you can't discard a particular chunk in the staged changes.

1) ~~Just un-stage the target chunk, and then discard. If the user can do it manually then it must be possible to perform programmatically.~~ A chunk that is moved from "staged" to "un-staged" might become part of a larger un-staged chunk, so I guess it could be pretty difficult to keep track of that.

**Comment by workgroupengineering** [comment]
![immagine](https://github.com/fork-dev/TrackerWin/assets/12531229/cedb9289-159e-4c41-a917-d224e249c830)

Could be added `x` button to discard all changes in `A` or `B`. I would prefer option `A`.
