### ISSUE TITLE
Misleading comparision on GitKraken?

### ISSUE THREAD

**Issue by 4imble** [ForkIssues/TrackerWin#1635]
I came across this, but it doesn't seem accurate. You would know better than me though.
https://www.gitkraken.com/compare/gitkraken-vs-fork

![image](https://user-images.githubusercontent.com/3931126/188153129-c08945a9-4622-4afd-b4f8-745346d6dad3.png)

**Comment by DanPristupov** [comment]
Well, what do you expect me to do?

**Comment by Otiel** [comment]
@DanPristupov Add a message to the Fork welcome screen to ask users to migrate to GitKraken, it's obviously better. 😆

**Comment by 4imble** [comment]
😅 cant tell if you are annoyed at me.

If it was me, I would state here which things you believe are wrong that could simply be because you have added new features which is great. I would then write an email to them pointing to your refutations and ask them to update appropriately.

I'm not expecting you to do anything just giving you a friendly heads up. Feel free to close this if you feel it's a waste of time.

**Comment by DanPristupov** [comment]
@4imble

> cant tell if you are annoyed at me.

No, absolutely not. It's GitKraken's advertisement page and I would be **very** surprised if they wouldn't show their product in a superior position 😀.

>  it doesn't seem accurate. 

They've missed that Fork has Command Palette, but it's a tiny detail. Otherwise I found their comparison pretty fair. 


And since we are here, I think GitKraken is a well-designed product 👍. I'm glad it exists and we have a competitive market where users do have a **choice** and are able to use what suits them best.

@Otiel 

> Add a message to the Fork welcome screen to ask users to migrate to GitKraken, it's obviously better.

No, we probably shouldn't 😀. I'm not good in advertisement and promoting 😀. We are good in programming and should keep doing what we do best.

**Comment by jerone** [comment]
Overview seems fair to me too. I don't care so much about GitKraken's features, except for:

> Fork does not integrate with Azure DevOps.

😞
