### ISSUE TITLE
Stashes not appearing in left pane

### ISSUE THREAD

**Issue by Reedbeta** [ForkIssues/TrackerWin#1640]
I've just noticed that my stashes are no longer showing up in the left pane, where there used to be a dropdown item between "tags" and "submodules". The stash does appear in the "all commits" pane. I tried restarting Fork, but it made no difference. I'm on 1.77.0.0.

**Comment by Otiel** [comment]
There is a new tab on the sidebar for stashes. 

It is mentioned on the changelog displayed when you upgraded to 1.77.0.

**Comment by curtusoft** [comment]
hello, can you bring back the stash on the left pane? is more usefull for me, because i change between branches a lot, and normally i need to use the stashes on every change, and it's anoying to have to change the tab to select a stash. and go back to the other tab to see the changes and branches...

Can you please add an option to put it back please on the left pane instead a tab?

**Comment by conanthedev** [comment]
I too preferred when it was in the left pane. Any special reason why it was moved to another tab?

**Comment by DanPristupov** [comment]
@paralemm We've moved stashes to a separate tab to make them easier to access when there are many branches in the repository. Previously, checking stashes required either collapsing the branches section or scrolling through it (both of which break focus).

**Comment by Reedbeta** [comment]
OK, I found it. I didn't realize there were tabs on the sidebar.

**Comment by DanPristupov** [comment]
@Reedbeta I will keep the topic open for some time because other users could have the same question.

You should probably unsubscribe from this post otherwise it will disturb you with notifications.

<img width="328" alt="Screenshot 2022-09-10 at 18 55 50" src="https://user-images.githubusercontent.com/618115/189493675-8f8f2901-4a23-4f27-9da1-6f79107fa995.png">

**Comment by simonlampen** [comment]
+1 for allowing stashes in the original place. While it might make it easier for people with many branches, that it a direct tradeoff for people with a few branches. Also even if your repo does have a lot of branches, many people will only track a few of those branches locally. It now makes it harder to push and pop stashes if you need to go back and forth on a few branches only.

**Comment by curtusoft** [comment]
> 

and i think this is the most common use case for a developer. It's insane to work on more than 5(max 10) branches simultaneously. I think an option somewhere in preferrences to select one or another will be a better approach.

And thank you for this great git client. The best of all :)

**Comment by lairtonb** [comment]
Yes, please, I understand this feature could have been to scratch your own itch, but it is hurting me. I always loved all the automatic updates. This is the first one that made me consider turning off automatic updates. It made working with stashes very inconvenient.

**Comment by kfina91** [comment]
Please add an option in the preferences to switch between the two options.

**Comment by tariel36** [comment]
Yes please, implement the choice where the stashes are. Separate tab is nightmare.

**Comment by simonlampen** [comment]
Can we please have the old layout back or an option to do so, this is driving me crazy 🤪

**Comment by Romaleks360** [comment]
yep, want this too!

**Comment by pwhe23** [comment]
I don't think you should optimize for poorly-managed repositories, please give us the option to move it back to the left (or just put stashes in both places). This is the first change that hurt my flow so bad I've had to revisit which git UI I'm using :(

**Comment by conanthedev** [comment]
@DanPristupov One month later, it is still not intuitive to have the stashes hidden in the separate tab. Any chance we can get the old layout back or an option to choose?

**Comment by Veilenus** [comment]
~~I just got hit with the auto-update myself and I'm mildly annoyed by the change. Please make it an option to bring the stashes back to the left-hand panel. But what bothers me even more than the move itself is the lack of discoverability. Currently, only the 15 most recent stashes are shown **at all** (with truncated names) and there is seemingly no way to expand either the names or the list. Parsing the commit list for a stash you might have created months ago is not a viable option. Please consider an update to this, otherwise, excellent tool.~~

Misunderstanding on my side. See answer below.

**Comment by DanPristupov** [comment]
@Veilenus stashes are in a separate tab on the sidebar.

**Comment by Veilenus** [comment]
> @Veilenus stashes are in a separate tab on the sidebar.

Thank you, I found it. I guess I never noticed the "Stash" icon in the upper menu bar before and mistook that for the change. Having an extra tab for the stashes is an alright solution as far as I'm concerned.

**Comment by DanPristupov** [comment]
It looks like the new layout adds unnecessary complexity to the UI.

The feature needs to be reimagined and we will likely roll the layout back until it's polished out (or we find a better approach).

**Comment by simonlampen** [comment]
Thanks Dan, I really love what you guys have created, it is one of the best source code tools I have used. This particular issue is just a disturbance in the workflow flow that I run into many times a day and it creates enough cognitive disturbance to be disruptive. Keep up the good work 😁

**Comment by vbasky** [comment]
It made me go crazy until I read through the thread to know it's in a different tab. I still prefer stashes on the left pane.

**Comment by mikenunan** [comment]
I think a good solution would be to have them back the side panel tree but leave the new tab as well, there are different cases where one or the other is more useful

**Comment by AColmant** [comment]
Hello,
I think the main issue here is UX. Since that changed, I cursed… Using the "stash" button. But reading the comments, I only discover today the dedicated tab (and it looks like I'm not the only one on this path). Knowing this, I don't find it really painful to switch tabs. However, it seems obvious to me that he should not have a different behavior because, in my opinion, it is this difference which creates a misunderstanding.

Thus, at first glance, I would say that the user should be able to choose between displaying in tree or in tab, but **for all the roots at once** (branches, remotes, tags, ...) to keep everything consistent.

Anyway, thank you for this great tool.

**Comment by obasille** [comment]
Hi, same thing happened to me.

Even though I use Fork daily, I'm only noticing now the branch/stashes/search toolbar in the left pane thanks to reading this issue. Feels kind of weird that I didn't saw it before, may be because of its odd location (not at the top of the left pane) or because of small icons?

Anyway not a big deal now that I've finally seen it, but I wanted to mention it.

Thanks a lot for your dedication on making Fork such a great tool!!

*edit:
I'm realizing I didn't look for this toolbar because there is already the big "stash" button in the main toolbar that lists stashes, so I though that's it for stashes.

**Comment by rmarskell** [comment]
> It looks like the new layout adds unnecessary complexity to the UI.
> 
> The feature needs to be reimagined and we will likely roll the layout back until it's polished out (or we find a better approach).

For what it's worth, I liked the change.

**Comment by ChristophLindemann** [comment]
@DanPristupov what about this solution:

**Have the main sections (Branches, Remotes, Stashes...) auto-collapse and auto-expand when selecting?**

When you select another main section, the currently selected section is collapsed. The state (collapsed/expanded) of all the nodes in the current section are remembered.
![image](https://user-images.githubusercontent.com/16814858/202114590-a33b6089-193d-4e1c-a381-b87369fe1056.png)
![image](https://user-images.githubusercontent.com/16814858/202114675-63ea94ed-451a-46e7-b1e8-c578f7883a02.png)

Now, when you reselect the previous selected main section, then current section is collapsed, and the newly selected section is expanded given the previously saved state (collapsed/expanded) of all the nodes. You might even select the node that was previously selected in that section.
![image](https://user-images.githubusercontent.com/16814858/202114753-b881d45f-98b7-4847-aa3b-f130c39aaab6.png)

Maybe you could also make all the root nodes always be displayedsomehow, so the current section kind of scrolls independent of the root nodes, when the list is long
![image](https://user-images.githubusercontent.com/16814858/202120597-25dbc6d8-bb30-4a0e-8ce1-52d292e1fb13.png)


And you could make this configurable, so ppl can select if they want to keep the current functionality or want the root nodes to auto-collapse. Maybe even make it configurable how many levels deep you want to auto-collapse (when having many remotes or branch levels).



**Another unrelated comment:**
I was also somehow taken by surprise, that the stashes were "gone".
Maybe you could present new features "better", and not only present the short change-list. Maybe a more thorough description of the new feature, how it works, why... (of course depending on the size of the feature) Kind of like the "What's new" in Visual Studio.

**Comment by conanthedev** [comment]
The stashes are back in the left pane in 1.79.2! Thanks @DanPristupov
