### ISSUE TITLE
Provide installer file SHA hashes. Common security transparency.

### ISSUE THREAD

**Issue by dbyte** [ForkIssues/TrackerWin#1679]
We would appreciate a fork.dev installer file/dmg checksum SHA being published for each new version, reducing security risks, as this is closed source and the current political situation should be taken into account.
FYI we have had some odd behaviour today downloading the Windows installer, poor dl performance maybe together with your new Let’s encrypt SSL certs, and a modified, non-discardable binary file after cloning a repo.

Be more transparent regarding security.

**Comment by DanPristupov** [comment]
> We would appreciate a fork.dev installer file/dmg checksum SHA being published for each new version,

1. Fork installers and all the bundled executable files are signed. If an installer would be compromised, modern operation system (both Windows and Mac) would not even allow you to run it!

2. It doesn't make much sense. Considering that intruder could have access to our certificates (in other words access to the build machine), it won't be a problem to calculate checksum of the modified file as well.

3. Each automatic update checks the downloaded files checksum (http://fork.dev/update/win/RELEASES). That's how incremental updates work.
```
01E02504CD61828CB296CE10769BC51468452B4B Fork-1.78.0-delta.nupkg 3444792
CE1D230FA18F75C5F791FDB2F7C85BB8E9D6E1EF Fork-1.78.0-full.nupkg 54218729
38E906510FB2F5770DAFD608FEFA806BAA36C2A0 Fork-1.78.1-delta.nupkg 1421358
5CBA8DA52E4830A1C1411407BDC2EA7B335755E4 Fork-1.78.1-full.nupkg 54173441
```

However, I believe, those checksums have zero impact on the security because of (1) and (2).

----

> FYI we have had some odd behaviour today downloading the Windows installer, poor dl performance

Fork.dev server is in NY and the installer file is not on CDN. The connection from Europe is quite slow. It takes me a few minutes to download the windows installer.


> a modified, non-discardable binary file after cloning a repo.

Check the log file (%localappdata%\fork\logs\fork.log) and use the feedback button on the toolbar.
