### ISSUE TITLE
Submodules -> Branches not updated via Fork

### ISSUE THREAD

**Issue by JasterX** [ForkIssues/TrackerWin#1697]
I’m using Fork 1.78.10 with an internal git instance of 2.36.1.

The bug is around submodules:
I added a submodule (“default” git repo -> origin:master).
I push updates to master in the submodule.

Now, when I update the original repo via pull (in Fork), the submodule is not updated, it remain on the commit it was created on.
If I go to the same repo, using the same instance of git in a console, I just run “git pull”, the module is correctly updated to the latest commit.

**Comment by DanPristupov** [comment]
Submodules are not updated on pull (at least by default, https://www.git-scm.com/docs/git-pull). Did you configure that somehow?

**Comment by CaseyHofland** [comment]
Would a "pull 'submodule'" menu option when you right-click a submodule be an idea? I feel like it would take care of these pull-problems entirely by just making it a feature instead of these automated checks because I still end up going inside-and-outside submodules to update to the latest version).

EDIT:
Nevermind, I get how it works now and it makes a lot of sense the way it is set up, just wasn't expecting it.
