### ISSUE TITLE
Remove window blue border

### ISSUE THREAD

**Issue by bergamin** [ForkIssues/TrackerWin#1923]
Very low priority, but the blue border around Fork's windows is a bit distracting. It also visually conflicts with a desktop utility I use for making windows always on top, but the main reason is that it's quite distracting. It makes the window look like it is focused when it isn't and it may make adjacent windows look focused when they aren't

![image](https://github.com/fork-dev/TrackerWin/assets/14339291/51d77780-ef48-4217-89a9-229aaec87523)

**Comment by bergamin** [comment]
Or at least make it possible to change the colour or toggle it on/off

**Comment by DanPristupov** [comment]
I think this border is part of Windows 10 design. I myself use Windows 11 and I don't see it.
<img width="585" alt="Screenshot 2023-05-31 at 17 14 40" src="https://github.com/fork-dev/TrackerWin/assets/618115/bf4d2a94-9b69-48ad-a367-7cf75cac4cc1">

**Comment by bergamin** [comment]
Oh, I see. Interesting. Your app is the only one I use that is built in the way that Windows does that. Happy to know on 11 this doesn't happen. I'll try it out on my personal PC as well which is 11

Thanks

**Comment by Otiel** [comment]
> I think this border is part of Windows 10 design.

This is true, but the border color should disappear when Fork is not focused, and that is not the case today.

See:
* Fork focused, Firefox in background:
![image](https://github.com/fork-dev/TrackerWin/assets/3851902/36dfb570-e5a5-4e19-b827-268a1153ee1d)
* Fork in background, Firefox focused:
![image](https://github.com/fork-dev/TrackerWin/assets/3851902/9dbe733e-b182-4146-8447-c797044ac37e)

**Comment by czdietrich** [comment]
I don't think this has anything to do with Windows 10. I can also see these lines shining through in Windows 11.
The windows have an explicit border set, but for the main window the border thickness is 0, therefore it's not visible:

<img width="605" height="76" alt="Image" src="https://github.com/user-attachments/assets/82e59507-963c-4121-a172-26d17fc70456" />

For other dialog windows it is set to 1 and therefore becomes sometimes visible, because layout uses floating number calculations:

<img width="608" height="81" alt="Image" src="https://github.com/user-attachments/assets/cc236b4f-3a6b-4e66-aa00-ff80f02e1eca" />

If this border is not meant to be displayed, I would suggest to either set border thickness to 0 or set `UseLayoutRounding` to `true` on every window to prevent this artifact produced by layout calculations:

<img width="623" height="701" alt="Image" src="https://github.com/user-attachments/assets/819f7ca0-e28b-4b98-b781-151dfb94e739" />
