### ISSUE TITLE
Full screen on main window prevents hidden taskbar to show.

### ISSUE THREAD

**Issue by rvlieshout** [ForkIssues/TrackerWin#199]
I'm letting my Windows auto-hide my task bar. It will pop up when I hover over it. However when Fork is on the foreground and open in fullscreen mode, the taskbar won't show any longer.

Windows 10
Fork 1.29.1.0

**Comment by DanPristupov** [comment]
Just want to say, that I couldn't find the problem yet.

Update: I wanted to say: "I couldn't find a way to fix the problem yet."

**Comment by rvlieshout** [comment]
@DanPristupov But were you able to reproduce the issue?

Both my machines show this behavior:

* Right click taskbar and select 'Taskbar settings'
* Switch 'Automatically hide the taskbar in desktop mode' to on

The taskbar will now only pop up when you hover your mouse over it. Op fork and make it full screen. You'll not be able to reach the taskbar (only by pressing the windows button on the keyboard or making another window the foreground application.)

**Comment by DanPristupov** [comment]
Sorry, it looks like a missed part of the sentence somehow.

I did reproduce the problem, spent some time fixing it but couldn't find a solution quickly. We will look into this again later.

**Comment by timoerlemans** [comment]
Any update on this?

**Comment by DanPristupov** [comment]
No, we couldn't fix it yet. Even a new WPF application with a custom chrome has such problem.

**Comment by obror** [comment]
any update on this?

**Comment by DanPristupov** [comment]
Currently I don't know a way to fix this.

**Comment by DanPristupov** [comment]
The problem with the auto-hide mode task bar may be fixed in Fork 1.50

**Comment by obror** [comment]
Great news!Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding --------Fra: Dan <notifications@github.com> Dato: 29.05.2020  16:54  (GMT+01:00) Til: ForkIssues/TrackerWin <TrackerWin@noreply.github.com> Ko: obror <obror98@gmail.com>, Comment <comment@noreply.github.com> Emne: Re: [ForkIssues/TrackerWin] Full screen on main window prevents hidden taskbar to show. (#199) 
The problem with the auto-hide mode task bar may be fixed in Fork 1.50

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ForkIssues/TrackerWin/issues/199#issuecomment-636017877",
"url": "https://github.com/ForkIssues/TrackerWin/issues/199#issuecomment-636017877",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rvlieshout** [comment]
Seems to be resolved in 1.50
