### ISSUE TITLE
Update fork version 1.89.1.0

### ISSUE THREAD

**Issue by ElizabethGaneshan** [ForkIssues/TrackerWin#2014]
After the recent update of fork version 1.89.1.0 ,for every actions (fetch, push, pull, merge) that I perform on git fork, it is asking for the password always. 
It is a very big problem that I ma facing now, because I do keep pushing the codes very often.
I kindly request you to provide a solution on this ASAP.

**Comment by angularsen** [comment]
Since CLI commands worked without asking for credentials, I switched Fork to use my installed Git instead:
`File > Preferences > Git > Git Instance` changed from `2.42.0.windows.2 - Fork git instance` to whatever you have installed. In my case, I had just updated Git so the versions were identical.

This solved the problem with Fork asking about credentials every time, until this bug is fixed.

Related issue #1998
