### ISSUE TITLE
fatal error - couldn't dynamically determine load address for 'SystemFunction036' (handle 0x780000), Win32 error 127

### ISSUE THREAD

**Issue by Retnu86** [ForkIssues/TrackerWin#2051]
Hi,

since the last update I receive this error frequently (screen from fork.log):
![image](https://github.com/fork-dev/TrackerWin/assets/123059475/ae942ebe-5240-4aab-a754-d76f1d9453e7)

Same error from another source though:
```
2023-10-17 17:17:34.570 Git request failed 'commit --file="C:/******/**/****/.git/COMMITMESSAGE"':
      1 [main] perl (12624) C:\Users\*****\AppData\Local\Fork\gitInstance\2.42.0.2\usr\bin\perl.exe: *** fatal error - couldn't dynamically determine load address for 'SystemFunction036' (handle 0x610000), Win32 error 127
```
The commit subject stays empty too (except for the ticket number).

Is this an error on my machine or has this something to do with fork?

**Comment by DanPristupov** [comment]
I've never heard about such a problem, so I think it's the problem of your machine. It's not related to Fork, it's unmodified git from https://git-scm.com.

`SystemFunction036` is a Win32 function from `C:\Windows\System32\advapi32.dll` (not sure what it does though). Most likely something is corrupted on your computer.

1. Try to reboot.
2. Try to reinstall Fork using the latest installer from https://fork.dev, that will reinstall the internal git instance. However, since the problem occurs in multiple files (`perl.exe` and `ssh.exe`) reinstallation will likely not help.

**Comment by Retnu86** [comment]
Well, it looks like reinstallation helped. Also feels way smoother now. Don't know what's going on there.
Just received the same issue from a colleague, so it is at least not only my machine.
