### ISSUE TITLE
Offer quick pull/rebase or pull/merge when pushing while behind

### ISSUE THREAD

**Issue by skttl** [ForkIssues/TrackerWin#2067]
![image](https://github.com/fork-dev/TrackerWin/assets/3726467/a8d1a0b9-7792-414a-b9d8-3566e95ee73b)

If I try to push something, but I am behind, I get a dialog saying push failed because I am behind.

In this situation, it would be nice if the dialog had a button, that would pull latest changes and rebase/merge, and afterwards do the push again.

Now I have to close the dialog, pull and then push again.

**Comment by DanPristupov** [comment]
Synchronization/merge is a critical task which should not be performed automatically. I don't want to give a user a way to merge changes and push the result in one click (which might be occasional).

> Now I have to close the dialog, pull and then push again.

Yes, and this is the intentional behavior which reduces the chance of a user error. There is enough time to figure out why push has failed and how to fix that.
