### ISSUE TITLE
[Feature Request] Allow cherry-picking merge commit

### ISSUE THREAD

**Issue by mloskot** [ForkIssues/TrackerWin#213]
Fork 1.30 does not support `git cherry-pick` option `-m` to specify parent number, so picking changes via merge commit is not supported.

![fork-1 30-cherry-pick-merge-commit](https://user-images.githubusercontent.com/80741/55091514-df254400-50a8-11e9-980f-f073ad5c7f0e.png)

**Comment by DanPristupov** [comment]
Create a commit custom action.

**Comment by mloskot** [comment]
Thanks, this does the trick

![fork-custom-action-cherry-pick-merge-commit](https://user-images.githubusercontent.com/80741/55099753-367ee080-50b8-11e9-9da8-5b680de90c4a.png)

It would be nice to have the confirmation prompt before the action is applied though. Similar to the `Cherry-pick Commit...` command.

**Comment by DanPristupov** [comment]
> It would be nice to have the confirmation prompt before the action is applied though. 

Interesting idea. I'll think about it. However, this could be a very broad topic.

**Comment by KPhi** [comment]
Are there plans to add native support for cherry-picking merge commits instead of using a custom action as a workaround?
It is rather confusing UI-wise when I get the option to cherry-pick a commit which then doesn't work for certain commits. On the other hand, the custom action has this problem reversed: it doesn't work for most commits but just for some. In the end I have two commands in the context menu which both don't always work.

**Comment by DanPristupov** [comment]
Yes. Vote for this issue if you need it.

We sort features by importance (i.e. by number of 👍 in the first commit). https://github.com/ForkIssues/TrackerWin/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DanPristupov** [comment]
Hi. We implemented ability to cherry-pick and revert merge commits in Fork 1.40.

**Comment by mloskot** [comment]
Thank you!
