### ISSUE TITLE
Git Error: failed to read references

### ISSUE THREAD

**Issue by YunJaeLee827** [ForkIssues/TrackerWin#2265]
Hi,
since the update to 1.99.2.0 today, I get  in a while following pop up:
![GitError](https://github.com/user-attachments/assets/f041a59d-5818-4032-9fd7-ffde1ce0fb5c)

**Comment by DanPristupov** [comment]
Hi. Please run `git pack-refs` in the command line

**Comment by achimmihca** [comment]
I also run into this. Would be nice if Fork would also handle the "peeled" packed-refs format, in addition to "fully-peeled". 
Any reason against this?

**Motivation**
We have a webapp that uses JGit to manage repositories. Looks like JGit uses "peeled" format by default.
That said, running packRefs command switches to "fully-peeled" also in JGit.

Unfortunately, the team decided against this change because we use Fork Git client only sometimes when debugging a repo that is managed by our webapp.

**Comment by DanPristupov** [comment]
@achimmihca 

> Any reason against this?

Yes, git switched to 'fully-peeled' format of the packed-refs backend in 2013. We don't have a time to implement and maintain support a ~13-years-obsolete format.
