### ISSUE TITLE
How to change the location of the install folder 

### ISSUE THREAD

**Issue by michisnewsletter** [ForkIssues/TrackerWin#2324]
If a install Fork on Windows, the installation will be stored in `C:\Users\[USER_NAME]\AppData\Local\Fork\Fork.exe`

During the installation, I don't have any options to change this.

Is there a command-line option ot change this folder ?

Thanks
 Michael

**Comment by DanPristupov** [comment]
No, you can't change the installation folder.

**Comment by trezum** [comment]
Can you make this possible? :)
@DanPristupov

**Comment by DanPristupov** [comment]
No. We use https://github.com/velopack/velopack and it can only be installed to %localappdata% in order to make automatic updates work.

**Comment by cameronbell97** [comment]
It would be nice if the option to install in locations other than AppData was available, even if it was a version with auto-update functionality ripped out that's only available on package managers (because people that choose to use package managers like WinGet or Chocolatey usually prefer to keep updating their apps through them anyway).

It's common practice to block applications running from AppData for security reasons, especially in businesses & enterprise. I often run into an issue specifically with Fork where I cannot launch it except through the installer, so every morning I have to re-install it on my machine just so I can get it to open. I can't even uninstall it because the uninstaller runs from AppData 🙃

**Comment by ritablob** [comment]
I agree. It would also prevent users from having to install the same app on multiple windows users. I like to keep my work account and regular account separate, but I still want to access some of the same apps that I have installed on my regular account, from my work account. I get that it isn't a technical possibility right now, but just something to consider in the future.

**Comment by DaMa-IT** [comment]
> No. We use https://github.com/velopack/velopack and it can only be installed to %localappdata% in order to make automatic updates work.

That's quite the poor justification, considering Windows and MacOS have various other ways to deploy application updates in a more controlled manner (winget, Windows Store, various enterprise solutions).

Not to mention not all of us _want_ automatic updates to be on bleeding edge either - something in Fork 2.66.7 MacOS broke for us for example, so we've had to just block them until we can determine the cause/solution.

For the moment we've worked around this on Windows by just building our own installer. Extract the downloaded EXE, navigate to `.\lib\app` and delete the "Squirrel.exe" file since it's no longer needed (this is the damned installer that triggered the whole "apps in %APPDATA% movement), and you effectively have a portable version of the app - packaging that to an MSI and deploying that to Staff. Just would be nice to save us that extra step, or even just providing a 'Portable' version of the app in a ZIP.
