### ISSUE TITLE
No conflict resolver after staging file with conflict

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#271]
1) merge with conflicts
2) double click on file with conflicts (forget how Fork works, expect to open conflict resolver) - file staged
3) unstage file - only 
```
<<<<<<< HEAD
xxx
=======
yyy
>>>>>>> origin/dev
```
in diffs, no option in menu to mark conflict not-resolved

**Comment by DanPristupov** [comment]
Git considers file as 'resolved' once it's staged. We can't show an 'unresolve' option, because file is not conflicted anymore (i.e. it becomes same as all other files).

**Comment by JackZylkin** [comment]
Could you give a stern warning when trying to stage a file that still has conflicts?
Or block that operation altogether?

**Comment by andyg336** [comment]
I know this is an old bug report, but it's stopping us advocating our team members using Fork.

The ability to rather silently stage files and thus discard incoming changes in a merge conflict is a deal breaker. Other clients like Git Extensions and Source Tree have you address conflicts in quite a deliberate way.

Whereas here the UI pattern is the same, and it's common for users less versed in Git to just click stage, see the issue has gone away, commit and ignore it. 

Granted this isn't good behaviour on the user's behalf, but Fork is otherwise really user friendly for non-coders (artists / designers collaborating on a games) and it's a shame this can be such a big problem.

**Comment by DanPristupov** [comment]
That problem has been fixed in Fork 1.55 but I forgot to report that. Now Fork checks whether the file is merged before each stage.
