### ISSUE TITLE
Cannot open any repository after latest update

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#282]
I updated to v1.33 for Windows this morning, and did an Intel Firmware update at the same time. Since the restart, Fork cannot open any repositories on my machine (but SourceTree, for example, still can).

This might be a recurrence of #184; I can confirm that %localappdata%\fork\gitinstance does contain a folder named 2.20.1.

**Comment by DanPristupov** [comment]
1. Check the log file `%localappdata%\fork\logs\fork.log`
2. Try to reinstall Fork.

**Comment by ghost** [comment]
Uninstall/reinstall did not fix the problem. The very end of the log file contains the following:

I 2019-05-20 11:30:31.255 Git instance successfully installed at 'C:\Users\********\AppData\Local\Fork\gitInstance\2.20.1\bin\git.exe'.
W 2019-05-20 11:30:41.622 Git request caused error 'config --global --replace-all user.name "Jon Hill"':

**Comment by ghost** [comment]
This might be relevant: Git Credential Manager for Windows just popped up and requested access to the network. I granted it, but the issue remains, even after another uninstall/reinstall.

**Comment by DanPristupov** [comment]
Can that be an antivirus issue?

**Comment by ghost** [comment]
I deactivated my antivirus for the location where I keep my repositories (D:\GitProjects), and did another uninstall/reinstall cycle. I see the following blank dialog, and the same error in the log file as above.

![image](https://user-images.githubusercontent.com/6400281/58020857-47b8fc00-7b01-11e9-8d3f-c6430c9a059b.png)

**Comment by DanPristupov** [comment]
I mean, the antivirus can deny Fork to run git process, which is located at `%localappdata%\fork\gitInstance\2.20.1\`. Please check the antivirus activity log.

I didn't make any changes related to the git instance in the latest update, so I suppose that the problem is on your side (most likely).

Try to run `%localappdata%\fork\gitInstance\2.20.1\bin\bash.exe` and type some git command (e.g. `git config --list`). Does it work?

**Comment by ghost** [comment]
`git config --list` works as expected.
I can try to make my antivirus ignore those executables. Exactly which ones are involved?

**Comment by DanPristupov** [comment]
All the executables in %localappdata%\fork\, Generally, Fork.exe + all the git executables (there's a lot of them).

Could you send me the Fork log file to winsupport@forkapp.io?

**Comment by pSatishC** [comment]
I have the same error - the fork.log has no information to indicate there's a crash but I copied it further below anyway.

The Event Viewer has a couple errors and the details are in the attachments
[ev1000.txt](https://github.com/ForkIssues/TrackerWin/files/3500904/ev1000.txt)
[ev1026.txt](https://github.com/ForkIssues/TrackerWin/files/3500905/ev1026.txt)

**fork.log**
```
D 2019-08-14 14:54:28.401 Loading settings.
I 2019-08-14 14:54:28.513 Start ipc server Fork_233536_Pipe_AskPass
D 2019-08-14 14:54:28.516 Waiting for next cross-process event '242'
I 2019-08-14 14:54:32.819 Fork 1.37.2.0 at C:\Users\whoami\AppData\Local\Fork\app-1.37.2\Fork.exe
I 2019-08-14 14:54:32.819 Git Location: C:\Users\whoami\AppData\Local\Fork\gitInstance\2.20.1\bin\git.exe
I 2019-08-14 14:54:32.819 Log target: AppData log file
I 2019-08-14 14:54:32.944 Last update check: 13-Aug-2019 5:35:35 PM. Next one: 14-Aug-2019 5:35:35 PM
I 2019-08-14 14:54:33.069 Restoring 0 sessions.
D 2019-08-14 14:54:33.114 Saving settings.
I 2019-08-14 14:54:33.148 Main: 698, Window: 5286, WindowLoaded: 249, UiReady: 80, Total: 5615
```

I am on Windows 10 Enterprise 1809 (17763.652) and Fork is 1.37.2.0

**Comment by DanPristupov** [comment]
@pSatishC I checked the errors, one of them has the following call stack:

```
Exception Info: System.Runtime.InteropServices.COMException
   at Microsoft.WindowsAPICodePack.Dialogs.CommonOpenFileDialog.InitializeNativeFileDialog()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at Fork.UI.OpenDialog.SelectDirectory(System.String, System.String, System.String ByRef)
   at Fork.UI.Commands.OpenRepositoryCommand.Execute()
   at Fork.UI.MainWindowMenuManager+<>c__DisplayClass16_0.<CreateFileMenuItems>b__3(System.Object, System.Windows.RoutedEventArgs)
```
The call of CommonOpenFileDialog has crashed. Did you try to open a repository?

P.S. I found a similar issue, but there's no details: http://arkservermanager.freeforums.net/thread/6272/oops-internal-error-first-startup

**Comment by DanPristupov** [comment]
@pSatishC I'm just thinking out loudly. Is that possible that you run Fork (1.36?) with elevated rights, then it performed the automatic update and now the new (1.37) instance is not accessible?

Try to run Fork as administrator. Is the behavior any different?

**Comment by pSatishC** [comment]
Yes, I was trying to open a repository using the File - Open Repository menu.

I am not sure about the admin/elevation. I think this issue was there for the last few versions - it worked alright earlier. When I saw this on 1.35, I updated and found the same behaviour. So I uninstalled Fork 1.37 (auto-updated) and reinstalled 1.37 downloading the new setup. Still the issue persists.

I will check launching Fork as Administrator and report back tomorrow.
Git commands (stash, commit, push) all work fine as does opening a repo from default Git folder listing by double-click.

**Comment by DanPristupov** [comment]
Try to open repos by dragging them to Fork from Explorer.

It looks like OpenFileDialog crashes, but I really don't have an idea why.

UPD: I found the source here (https://github.com/aybe/Windows-API-Code-Pack-1.1/blob/master/source/WindowsAPICodePack/Shell/CommonFileDialogs/CommonOpenFileDialog.cs), but it's not much helpful

UPD2: It looks like the following COM class is not available or corrupted:

` internal const string FileOpenDialog = "DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7";`

Here's a similar issue:

https://stackoverflow.com/questions/29929862/exception-from-hresult-0x80040111-class-e-classnotavailable

Do have disabled Windows themes (or High Contrast mode) may be?

**Comment by pSatishC** [comment]
> Do have disabled Windows themes (or High Contrast mode) may be?

Yes, I have High Contrast mode enabled always.
And this is the issue - I switched back to normal Windows theme and File Open Repo works fine.

I could have never imagined that these two were related. Thanks for your help.

**Comment by DanPristupov** [comment]
OK, I don't know how to fix that. I must use that library (`WindowsAPICodePack`), because WPF doesn't have a native OpenFileDialog.

However I can reduce the confusion with the following:

- Don't crash
- Show a message dialog with a problem description and a proposal to use drag and drop or disable High Contrast theme.

P.S. Do you have any idea why this could be related to the Fork update?

**Comment by pSatishC** [comment]
I noticed that if I use `OpenFileDialog` from `Windows.Forms` there's a way to fall back to the classic File dialog. I tried opening one in a small sample WPF app and it seems to work with a High Contrast theme set.
```c#
private void btnOpenFile_Click(object sender, RoutedEventArgs e)
{
    System.Windows.Forms.OpenFileDialog dlg = new System.Windows.Forms.OpenFileDialog();
    try
    {
        dlg.ShowDialog();
    }
    catch (Exception ex)
    {
        System.Runtime.InteropServices.COMException comEx = ex as System.Runtime.InteropServices.COMException;
        if (comEx != null)
        {
            if (comEx.Message.Contains("0x80040111") && comEx.Message.Contains("{DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7}"))
            {
                dlg.AutoUpgradeEnabled = false;
                dlg.ShowDialog(); // show again with AutoUpgrade disabled
            }
        }                
    }
}
```  
<br>
   
> P.S. Do you have any idea why this could be related to the Fork update?

I think this used to work earlier because I have been using Fork for quite sometime and did not come across this issue earlier. MS may have changed something that caused this (?)  

Anyway, I have read some people claim that Win 10 1903 fixed this but I have not verified it.

**Comment by DanPristupov** [comment]
Regarding the initial problem.

Please try to change the git instance path to something, which is more short. We added ability to change git instance using `%forkgitinstance%` environment variable in Fork 1.39.

The easiest way to create an environment variable is to run `cmd.exe` and run the following command:
> `setx forkgitinstance C:\gitInstance\2.20.1`
