### ISSUE TITLE
Project directory empty after clone failed

### ISSUE THREAD

**Issue by tvequaud** [ForkIssues/TrackerWin#319]
During a long clone action, a colleague finally killed Fork... And everything in its projects directory disappeared. Which is really bad cause it was its windows home directory. Yeah, he lost a lot (documents, downloads, software configurations) !

But the weirdest thing is the installation directory of Fork... Partially disappeared too : *.exe, *.json, logs directory...

Windows 10
Fork 1.34.2.0

**Comment by DanPristupov** [comment]
I hope you managed to recover the important info. Otherwise try to use recovery applications, they work pretty well.

Regarding the accident. Do I understand correctly, that the clone operation was taking too long and your colleague decided to terminate Fork process and then a lot of folders got removed?

This sounds very strange.
1. Removing home directory is a looong operations, it should take at least a minute.
2. Terminated application cannot remove files. It's dead.
3. I checked the source code and the only (!) recursive delete (with subdirectories) in Fork happens when user deletes a submodule.

It's very unlikely that Fork is involved there, however I will try to reproduce that.

I'd recommend you to brainstorm what else could cause that. Any deinstallation may be?

P.S. It's usually very difficult to investigate cases happened to a colleague...
