### ISSUE TITLE
[Feature Request] Don't open all folder in the branches view

### ISSUE THREAD

**Issue by alvinmeimoun** [ForkIssues/TrackerWin#32]
Hi

I currently manage a project that contains a lot of branches dispatched in folder (using / in name)

Example of my branches : 
generic/dev/master
generic/dev/feature/feat1
generic/release/1.0.1
generic/backup/2018_08_01
specific/dev/master
...

And when i open the origin tree, all my folders are opened and i take a lot of time to find my branch.
It will be great to allow to the user to configure Fork to not open these folders automatically

**Comment by zrpfpr** [comment]
+1 

In a big repo, with a lot of remote branches and folders, it is quite annoying. Please, do not ignore this feature

**Comment by DanPristupov** [comment]
Will Expand All/Collapse All options make your experience better?

**Comment by zrpfpr** [comment]
Yes! Starting with all collapsed and then, open one by one (or expand all if you want, of course). Thanks!

**Comment by DanPristupov** [comment]
I mean the Expand/Collapse items in sidebar **context menu**.

**Comment by alvinmeimoun** [comment]
Hi,
I'm agree that the "expand/collapse all" button could be a great feature.

My base idea was to let the user choose this in settings, if at startup all are expanded or all are collapsed. 

Now i just have this following idea, how about saving the state ? Keeping the button to collapse/expand all but is it complicated to implement the save of expanded and collapsed branches ? And i think this idea can be a separated feature request and keep the focus in priority to collapse/expand all feature

**Comment by DanPristupov** [comment]
I'm very busy right now to answer in details. So, very briefly:
We don't ignore sidebar and already working on its improvements. In Fork 1.28 the Repository Manager sidebar remembers open items even when you restart the application (we just test the features there).

Regarding sidebar in repository view:
- Repository sidebar will remember expanded items for each repo and restore them after restart
- No subitems will be open automatically
- On first run the Local branches section will be fully opened, the rest is closed
- Ability to sort items alphabetically or by recently used

ETA: 1.30-1.31

**Comment by mycalingram** [comment]
Just to add my own vote. I work for an organization that has roughly 500 people working on one of our product repositories. At any given time, we can have anywhere from 100-400 branches that are in active development on a single one of our repositories. Many of our teams and individual contributors have adopted to putting their branches into a folder to make organizing and finding their branch a little cleaner and easier. 

At the time of this writing, there are 298 branches on a particular repo I am workin in with 28 parent level folders housing a majority of the branches. 

As a convert from Sourcetree (for a variety of reasons), they had the collapsed by default behavior and also persisted the users's expanded items. It was incredibly buggy though and would often reset back to fully collapsed. Since it collapsed everything by default, it was a manageable annoyance. 

"Collapse/Expand All" or "Collapse by Default" is not really just a nice to have for my organization, it's a necessity due to the structure of our repository.

**Comment by DanPristupov** [comment]
Just as reminder to myself: we also need ability to **filter** the list of branches on the sidebar

**Comment by DanPristupov** [comment]
> * Repository sidebar will remember expanded items for each repo and restore them after restart
> * No subitems will be open automatically
> * On first run the Local branches section will be fully opened, the rest is closed
> * Ability to sort items alphabetically or by recently used

I just published 1.31 with those features :)
