### ISSUE TITLE
Support Shift+Wheel to scroll horizontally

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#321]
It would be nice to be able to scroll horizontally with <kbd>Shift</kbd>+ mouse wheel (commit list, file view when "Word wrap" isn't checked...).

**Comment by ArmandDelessert** [comment]
Yes, it would be nice to support that! And support the [horizontal scroll wheel of the mouse](https://i.stack.imgur.com/Oggsj.png). That's one of the reasons I came here.

**Comment by rotorgames** [comment]
@DanPristupov any updates? That's most important thing cuz if a commit is in a lot of branches we rather can't read a commit's description because all horizontal space in the commit list is filled by branch names. 

Also, it's really important to get scrolling in files (staged/unstaged) cuz for now, if we use `View as Tree` all file names are truncated.

@DanPristupov could we get ETA for the feature? 

Thanks.

**Comment by kambala-decapitator** [comment]
in diff view it works already, not sure about other places though
