### ISSUE TITLE
Lightweight checkbox in "Create Tag" window

### ISSUE THREAD

**Issue by Gama11** [ForkIssues/TrackerWin#327]
There are [significant differences between "lightweight" and "annotated" tags](https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags). For instance, the former won't show up in `git describe`, but it's what Fork seems to create by default (unless you enter a message?).

It would be nice if the "Create Tag" window had a checkbox for this, similar to SourceTree (there tags are even annotated by default, with an explicit "not recommended" message for lightweight tags):

![](https://i.imgur.com/0p2eEqP.png)

**Comment by DanPristupov** [comment]
That's correct. A tag will be lightweight, until it has a message.

**Comment by Gama11** [comment]
Gotcha. I'd like to have the option to make tags without messages non-lightweight too. :)

**Comment by sinbad** [comment]
My 2c here: Git recommends that you don't use lightweight tags except for temporary pins for your personal use. Lightweight tags don't show up in `git show` or `git describe` and generally behave unintuitively compared to what most people expect when creating a tag. In practice most people expect the behaviour of annotated tags by default, with or without a message..

**Comment by DanPristupov** [comment]
Thank you for the explanation. 

OK, what about vice versa? What if we always create annotated tags? Is there a reason to have the ability to create lightweight ones?

**Comment by Gama11** [comment]
Personally I wouldn't mind that since I don't really have a use case for lightweight tags. But perhaps others do?

**Comment by sinbad** [comment]
I do think defaulting to annotated is what more people would expect. I personally never use lightweight tags except by accident, although I can imagine they could be useful for special cases or automation, say for temporary tags while tracking down an issue. But even in those cases I don't think annotated tags have very much of a downside in a GUI driven case - they create a tiny amount more data but it's negligible.

I suspect the main use for lightweight tags is to save time on the command line (no launching of the editor to prompt for messages) when doing quick / temporary things rather than full release tags.

**Comment by DanPristupov** [comment]
I think we don't need an option then.

To make the behavior change more clear I will:
* Mention in the release notes that tags will always be annotated.
* Update the dialog description to say 'Create **annotated** tag...'
<img width="500" alt="Screenshot 2019-09-09 at 17 46 39" src="https://user-images.githubusercontent.com/618115/64545835-ca243080-d329-11e9-946f-0d47efdd9fe8.png">

This update is going to be part of the 1.39 release which is planned for this Friday.

**Comment by DanPristupov** [comment]
I just released the 1.39 update which always creates annotated tags.
