### ISSUE TITLE
"Select SSH key" does not work on Windows

### ISSUE THREAD

**Issue by clounie** [ForkIssues/TrackerWin#343]
If I generate an SSH key via Fork, it creates that key in the `C:/Users/Myuser/.ssh/` folder, and lets me select it (fantastic)

However, for some reason it will _not_ let me select an existing key in that same folder. 

The UI says "**Select** or generate a new key..." - which I assume means I can use an existing key in that same folder which Fork generates keys in?

Fork for Windows 1.35.0.0

**Comment by DanPristupov** [comment]
I copied my keys from macOS and Fork saw them without a problem.

Please ensure that you have both private and public parts of the key in the directory.

**Comment by clounie** [comment]
Could you make the public key optional? It's not necessary for the SSH authentication/authorization process unless I'm Github..

**Comment by DanPristupov** [comment]
Because Fork must show the user how the public part (fingerprint) of the selected key.

**Comment by clounie** [comment]
I'm confused. 

1. Git Fork on Mac works fine because it hooks into the Terminal's SSH agent (I believe?)
    * Same with Git Kraken - If I specify "Use SSH Agent" in Git Kraken, it works fine.
2. The SSH agent does NOT have my public key on either computer, and it works fine. 
3. But for both Git Fork and Git Kraken, I need the private + public keys if I can't use SSH agent (like for Windows) ?

Why is the public key needed, when the generic SSH agent works perfectly fine with only the private key? 

Obviously you have good reasons for it, as always. But I am not following the explanation - sorry..

**Comment by DanPristupov** [comment]
You can use the default SSH agent, this is the default option. You just need to ensure it's configured, because Fork uses standalone git instance. Then you don't need a public key.

However, Fork has an alternative way for users who use SSH first time. They can just select the key, copy the public part and paste it to their GH/BB/GL account.

So, you can use default SSH agent and configure it on your own (like in Mac) or use a slightly easier way provided by Fork.
