### ISSUE TITLE
"View on GitLab" broken if project is created in a subgroup

### ISSUE THREAD

**Issue by gamecentric** [ForkIssues/TrackerWin#364]
Verified in Fork for Windows 1.36.0.0

Steps to reproduce:
- In GitLab create a subgroup and a repository into that subgroup
- In Fork, clone the repository. Notice that the URL is something like https://gitlab.com/account/group/repo.git
- In Fork, click on "Open in" and the on "View on GitLab"
- A web browser opens for https://gitlab.com/account/repo.git, which produces a 404 Not Found error, since the URL is incorrect ("/group" is missing)

**Comment by ZaLiTHkA** [comment]
just a quick note: this issue still exists in `1.41.0.0`..

not sure if the behaviour has changed since this issue was opened, however the link actually opened by Fork equates to using the top-level group namespace, not the current account namespace.

for example:

* Actual project URL: `https://gitlab.com/company-group/subgroup-1/subgroup-2/project`
* "View on GitLab" opens to: `https://gitlab.com/company-group/project`

**Comment by DanPristupov** [comment]
This issue should be fixed in 1.42. Please check for updates.

**Comment by gamecentric** [comment]
Confirmed fixed in 1.42.0.0
