### ISSUE TITLE
Better search UI in changes

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#394]
![Fork_2019-08-15_09-52-29](https://user-images.githubusercontent.com/7280273/63069794-992b2880-bf42-11e9-9e2a-faefd1558579.png)
At now I have to click on button on show textbox to enter query. Why not just always show text box in place of empty space between 🔎 and buttons at the right side?

**Comment by Otiel** [comment]
To the question "why", I'd answer:
* To keep the UI minimalist and clean as I imagine this feature is more often _not used_ than _used_ for most users.
* To prevent accidental key types that would filter out files without you noticing.

So I'm fine with the current implementation.

**Comment by DanPristupov** [comment]
I agree with @Otiel. Search field is needed only from time to time and it is better to keep it hidden the rest of time.

Since we are here, I'd like to ask to create more meaningful and less opinionated subjects. For example instead of "Better search UI in changes" it should be "Keep filter field visible all the time".

**Comment by sm-g** [comment]
![Fork_2020-04-18_08-00-17](https://user-images.githubusercontent.com/7280273/79629192-e6097380-814f-11ea-95f8-418e0f5a0ab1.png)

@DanPristupov however search in sidebar always visible. (And looks like the same widget.) 
In my expirience, filtering branches is much more rare case than filtering local changes.
