### ISSUE TITLE
submodules detachedHEAD

### ISSUE THREAD

**Issue by erichfrazer** [ForkIssues/TrackerWin#432]
I'm not sure if this is a bug. I have a project that has 10 submodule references within it. 5 of the projects (C#) in the tree have submodules that are Git clones of the same online repo. I have "automatically update git submodules" checked in preferences. Now, I don't know what causes this, but when I push the "pull" button and it updates my main repo and all the submodules, frequently when I go down into the submodule and open it, I see it has a "detached head". Prior to the update, the head wasn't detached. It's as if something about the pull made the submodule heads go off the track. I'm not sure exactly how to reproduce this bug, but man is it annoying.

**Comment by DanPristupov** [comment]
I suppose this is how your submodule is configured:

https://stackoverflow.com/questions/18770545/why-is-my-git-submodule-head-detached-from-master

**Comment by DanPristupov** [comment]
I think the ability to change the default branch for a submodule might be a feature.

**Comment by erichfrazer** [comment]
I read that page you sent, and it's super confusing, ESPECIALLY since the main answer by 'mkungla' appears to be wrong, but full of interesting information. he even edited his post saying 'simba' has the right answer. So going into that one and reading it, he/she says "why is head detached after update?" "because the DEFAULT behavior of submodule update is checkout", and if you're checking out a specific commit by ID, you'll result in a detached head. He goes on to say "if you want the submodule merged with the remote branch (what branch?), use --merge or --rebase". I don't understand that. He said you can set up submodule.$name.update to merge or rebase by editing .gitmodule…. Is that what you're suggesting?

**Comment by DanPristupov** [comment]
OK, to be honest, detaching on update is the behavior I'm used to. I've never tried to change the default tracking branch.

My suggestion was to try to do that, i.e. to configure `submodule.<name>.update` as the post said.

**Comment by erichfrazer** [comment]
Yeah, crazy. The detaching scares me. Guess I’m not used to Git enough. Especially submodules.

**Comment by DanPristupov** [comment]
In practice, detached HEAD is kind of read-only mode. Do whatever you want, but the commits you make will disappear when you switch branch (because no branch points at them). Then reflog view mode might be helpful (Repository -> Show Lost Commits (Reflog)).

It would be nice if people who use submodules in their workflow share some experience regarding detached HEAD.

**Comment by felixhirt** [comment]
We use submodules quite excessively, because we have lots of projects which always use the same common base. 

To me, detached HEAD's are just how submodules work. I guess you could try to do something clever (like, when a submodule gets checked out, see if there is a branch on the tracked commit and if so, check out that one instead). But if you do that, i would make it optional to not confuse people who used git with different clients (or the cli) before.

That being said, i love that you check out submodules recursively on clone (unlike git itself...), so i might very well love a quality of live change like this as well once i worked with it

**Comment by erichfrazer** [comment]
Well, whatever the case, SourceTree (bleah!) does it right. That is, the workflow is “correct”, though I’m not sure what it’s doing under the hood.

 

Consider my main project, which contains directories A, B, C… Each of those directories has a submodule X.

A:

                X:

B:

                X:

C:

                X:

 

When I go into B, edit some code in X, and commit it, I want my visual git program to (eventually) recognize that the commits happened on A’s X and C’s X. It should say “downarrow” meaning I am not up to date. Fork Git already does this I think.

 

Next, when I go to A’s X and open it, and tell it to “pull”, it should pull from whatever the latest is, without being detached. Or even bored. 

 

I’m failing to understand why people are saying “it’s just normal for the heads to be detached”. This scenario seems so common, if it requires something special, esp for a visual git client, it should be done already. I think the SourceTree guys figured it out, though I have to play w/ it some more.

**Comment by felixhirt** [comment]
What you are describing should work with fork as well once you checked out a branch for each of your X-es because you make a change in one x and then pull that change in the others.

The thing with git submodules and detached heads is that if you clone or pull a repo, that repo has information about the tracked commit (not branch) of each submodule, and attempts to check out that specific commit for each submodule. Checking out a specific commit will leave the submodule repo in a detached head state (as it would if you manually checked out a specific commit).

More often then not, there will be a branch head on this commit of course (because in real life, we work on branches). Thats why i suggested to check out that branch instead of the commit, but that is something fork would have to do, git does not support that (afaik).

Can you describe what sourcetree does to alleviate this issue? While this behaviour makes sense for git, it is an issue for me as well. My life would be much easier if submodules would magically check out a branch instead of a commit (as long as its the "right" branch)

**Comment by erichfrazer** [comment]
Here is another submodule issue that bugs me:

I have projects A, B, and C that all depend on submodule X.

Because I don’t want to have to go through the whole submodule update process, when I build A, B, or C, they build binaries that necessarily have to be in submodule X, and copy the binaries into A->X, B->X, and C->X. If I were to go into A->X (the submodule) and commit and push, those binaries now become “the official ones” for B->X, and C->X. if I go back out of A-X and update B->X and C->X (doing a pull), Fork Git still thinks the binary files are changed. Even though they actually contain the same thing. I dunno, the dates are different? I don’t know exactly why.

 

Would there be a way… when fork git pulls down the latest BINARY files, to do a binary comparison, and if the files are binary-compat, UNCHECKOUT the files that are supposedly different? This would relieve all of my git problems…
