### ISSUE TITLE
[Feature Request] Allow filtering of branches

### ISSUE THREAD

**Issue by siburny** [ForkIssues/TrackerWin#44]
It would be nice if we could filter the list of branches. We use branching workflow in our work, so we have more than a thousand of branches in the remote repository.

**Comment by PohaoGit** [comment]
Can we have this feature any soon? I love Fork's UI but this feature is why I still use tortoiseGit.

**Comment by DanPristupov** [comment]
Vote for it :). I implement the most popular features first.

**Comment by valhristov** [comment]
I use Fork regardless of this feature missing and I silently suffer :)

![2019-03-18 16_41_40-Fork 1 29 1 0](https://user-images.githubusercontent.com/23195959/54542911-e9ef2300-499c-11e9-82aa-119af0295bcb.png)

**Comment by DanPristupov** [comment]
Branch filter is going to be introduced in Fork 1.31-1.32 (i.e. next month).

**Comment by DanPristupov** [comment]
Finally, the ability to filter sidebar items is here (1.35)!

<img width="232" alt="image" src="https://user-images.githubusercontent.com/618115/59963732-845c8680-94f7-11e9-8fb8-ac9dd3683769.png">

**Comment by id-ilych** [comment]
Filter in sidebar is nice! But filtering tree view is also important. As an extension of this feature request - filtering by remote. I have a fork (pun intended) of an open-source project. Most of the time I only care about my own modifications ('origin' remote) but ocasionally I need to reintegrate released version of an original project ('upstream' remote). So I'd like to see only local and 'origin' branches most of the time with posibility to un-hide 'upstream' remote without having to remove/re-add it. It would also be nice to hand-pick two or three specific branches so that all others are hidden from "All Commits" tree view.

**Comment by DanPristupov** [comment]
>  So I'd like to see only local and 'origin' branches most of the time with posibility to un-hide 'upstream' remote without having to remove/re-add it.

Shouldn't you 'star' the important branches then?

**Comment by id-ilych** [comment]
@DanPristupov Wow! So there is filtering for tree view! Never noticed these icons. Awesome! Thank you.

**Comment by PsyhoBelka** [comment]
is any possible solution to see ONLY branch-related commits? not commits in branch, that was merged to current branch (and all other merges for all branches) - only current branch commits?
orange - is currently selected branch and i don't want to see others

![image](https://user-images.githubusercontent.com/25059773/61056697-7e720b00-a3fc-11e9-89cc-2d02b4d465d3.png)
