### ISSUE TITLE
[Bug] Rescan Repositories removes folders and names

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#448]
Let's say I organise my repos to folders.
When I choose "Rescan Repositories" it deletes all folders, resets all repository names, removes all repos which I added manually from other folders.

I think it should delete not existing repos, add new ones and don't touch existing.
Also multiple folders for scan would be nice.

Version 1.39.0.0.

**Comment by jobec** [comment]
Fix this one, and I throw out SourceTree...

Fork should scan and follow the filesystem on startup, not the other way around.

**Comment by DanPristupov** [comment]
This was implemented in Fork 1.42 in November 2019.

<img width="578" alt="Screenshot 2020-01-20 at 10 49 11" src="https://user-images.githubusercontent.com/618115/72716452-801e4780-3b72-11ea-84d4-86369869a64f.png">

**Comment by jobec** [comment]
It's still a manual action.

I copy over a settings file upon install and set `RepositoryManager´->`SourceDirectories` to the right path.
But upon first startup, users don't see any repositories, unless they click the "hidden" rescan link.
IMHO, this is something that should run automatically on startup.

Looking and comparing with sourcetree:
* OR you have users manually add repositories, one by one.
* OR you follow what's on the file system.

now it gives the impression Fork follows what's on disk, but in reality, it doesn't.

**Comment by DanPristupov** [comment]
> IMHO, this is something that should run automatically on startup.

This is a long operation and may take ~10 seconds (or even longer for users with HDDs). It can't be run on startup.

> now it gives the impression Fork follows what's on disk, but in reality, it doesn't.

Fork imports the repos which are located on disk. However you can also add repositories manually.

**Comment by jobec** [comment]
Ok, I might have misunderstood Fork's functioning. The path it asks at the beginning, is for an initial loading of repositories. Not to keep an eye on a certain folder. So that init screen made me think in the wrong direction.

How about one of these?

* detecting that new folders were added/deleted and prompting users to do the rescan?
* Explicitly add a button to rescan, preventing users from having to go into preferences.
* Not asking users for an initial folder, giving them the impression it'll sync with that folder all the time?

Also, I would add button a somewhere to quickly open en repo. Dragging it onto fork is not that good of a UX. Also, that `Open` button at the top right doesn't do anything, unless you have a repo in the list already.

Quick comparison with sourcetree:
![image](https://user-images.githubusercontent.com/16192496/72718585-8282a080-3b76-11ea-9a16-a552206c1209.png)

**Comment by jobec** [comment]
Oh... just read Fork wont be free anymore in the near future... (#571)
Never mind the above...

I can't defend buying it for a large group of developers if there's SourceTree or VS  Code's extensions like GitLens & GitGraph

**Comment by DanPristupov** [comment]
@jobec 👍
Sorry, I must pay my bills.

**Comment by jobec** [comment]
Sure, I understand.

You've got a nice piece of software here. But like I said, I cannot defend the cost if there are alternatives :-(

Maybe it's an idea to make it free for open source developers/maintainers? Like IntelliJ does with it's PyCharm licenses. It'll give me the chance to still use it and contribute "ideas".
And like IntelliJ, it might give you a 'boot on the ground" with certain developers that introduce it in their company that way.

**Comment by decadence** [comment]
@DanPristupov if it was implemented you can close this issue so it won't appear in your task list.
I can't check it right now but I believe you made it work like we expected 👍

**Comment by decadence** [comment]
I checked this feature today and it works great. All of my folders are persisted after rescan.
Moreover I noticed if default clone folder contains folder with repositories Fork automatically creates this folder after rescan. Great job!

Only one thing I want to remind:
> Also multiple folders for scan would be nice.

But it can be separated issue if it's more suitable.

**Comment by DanPristupov** [comment]
> Also multiple folders for scan would be nice.
> But it can be separated issue if it's more suitable.

https://github.com/ForkIssues/TrackerWin/issues/474
