### ISSUE TITLE
Merge: Select Left/Right buttons are too far from diff lines

### ISSUE THREAD

**Issue by doxxx** [ForkIssues/TrackerWin#470]
In the merge conflict resolver window, the Select Left/Right buttons are too far from the diff lines they're linked to and disappear when the mouse is moved from the diff lines to click the button. The distance appears to be linked to the position of the diff lines in the scroll view.

Example:

![image](https://user-images.githubusercontent.com/677940/66216234-1ea19e00-e693-11e9-812c-35b32a7393cb.png)

**Comment by heneds** [comment]
This only occurs when using the zoom-in function. Ways to reproduce: 
1) Zoom in 
2) Open a merge 
3) Scroll so that the diff lines are closer to the bottom of the view
4) Hover the diff lines 

When you move towards the select button it disappears before you reach it.

Workarounds, either... 
* don't use zoomed mode 
* or scroll so that the diff lines are closer to the top of the view

**Comment by heneds** [comment]
Oops, was already fixed in 1.41. Thanks!
