### ISSUE TITLE
New Tab not functional

### ISSUE THREAD

**Issue by SteveALee** [ForkIssues/TrackerWin#486]
On WIndows under the toolbar there is a tab control but the + for new tab does nothing

![image](https://user-images.githubusercontent.com/618922/66699848-1aecc780-ece2-11e9-9e13-ee6ce83d54af.png)

**Comment by SteveALee** [comment]
I've now found that there is a X close 'button' that appears on hover. 

If  I close the the single tab when viewing repositry details the view changes to the repo overview list.

Surely opening a repo from the overview should ADD a new tab not replace the single tab.

Tab management seems a little broken right now.

**Comment by Otiel** [comment]
>there is a tab control but the + for new tab does nothing

It opens the Repository Manager ("New Tab"). If there's no repo opened, the Repository Manager is automatically opened, so yes, clicking on `+` does nothing as the Repository Manager is already opened. I don't see how that's an issue.

>Surely opening a repo from the overview should ADD a new tab not replace the single tab.

The Repository Manager acts exactly like the "New tab" page of any browser. You need to see it as an empty tab, enhanced with the list of repos in order to help you quickly open a repo. At least that's how I see it, it works fine for me.

**Comment by SteveALee** [comment]
Ahah I hadn't realised that. So the repository manager is effectlivly the default page in a new tab. And the slightly unusualy thing is when you close the last one it repopens a new tab immediateley :)

Now I understand that it works for me too.
