### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by SaebAmini** [ForkIssues/TrackerWin#491]
I recently came across Fork and wanted to give it a try, however the UI doesn't even show up for me:

![image](https://user-images.githubusercontent.com/6758734/66712885-e151b480-ede6-11e9-9ccb-7b257246078e.png)

The white rectangle is the UI for Fork 1.40.2.0. This is inside a VMWare Windows 10 VM.

**Comment by DanPristupov** [comment]
Disable hardware acceleration https://github.com/ForkIssues/TrackerWin/issues/237

**Comment by SaebAmini** [comment]
Thanks Dan, but that's not really a viable solution as it makes guest graphics slow as. Is it possible to make Fork not use hardware acceleration?

**Comment by Otiel** [comment]
Instead of disabling hardware acceleration for the whole VM, you could try turning off WPF hardware acceleration so that only WPF applications won't use hardware acceleration and thus render correctly (hopefully) in VMWare:

Set `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Avalon.Graphics\DisableHWAcceleration` to `1`.

See [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings).

**Comment by SaebAmini** [comment]
Thanks for the workarounds.

May I suggest adding the option to disable hardware acceleration to Fork as a future improvement?

https://stackoverflow.com/questions/2169600/how-does-one-disable-hardware-acceleration-in-wpf

**Comment by DanPristupov** [comment]
We'll try to add a config option to disable the acceleration. We'll see how it works out.

**Comment by DanPristupov** [comment]
In Fork 1.41 we introduced an option to disable hardware acceleration. I'm not sure if it works, but you can try it.

Open `%localappdata%\fork\settings.json`, find `DisableHardwareAcceleration` and set it to `true`

**Comment by SaebAmini** [comment]
Beautiful! I just tested 1.41 with `DisableHardwareAcceleration` set to `true` in a VMWare VM and can confirm it now loads perfectly.

Thanks for the super quick turnaround on this one!
