### ISSUE TITLE
Using SSH aliases not working within Fork

### ISSUE THREAD

**Issue by armacdonald** [ForkIssues/TrackerWin#498]
Have recently started using Fork on an existing GIT repo that was created via the command line. It was setup using an SSH alias, for example having...
````
Host github github.com
Hostname github.com
User git
````
in `~/.ssh/config` (in my user folder in Windows).
In this example, the URL for origin is `github:example.git`.

Fetching origin within Fork gives the error `ssh: Could not resolve hostname github: Name or service not known`, whereas, if I open the console from Fork (which should be using Fork's GIT installation) I can run `git fetch origin` and it works fine.

I assumed Fork was not accessing `~/.ssh/config` so tried adding the aliases to `Fork\gitInstance\2.20.1\etc\ssh\ssh_config` and that did not work either (although still works from the command line).

I can easily work around this by specifying the full ssh:// URL, so it's not a big problem. Would be nice to be able to work with aliases on the command line though as I have a list of various servers (with non-standard ports).

**Comment by DanPristupov** [comment]
You can try to switch git instance to your system one in Fork preferences..

**Comment by AndrewGodfrey** [comment]
I am hitting this too, with 2 differences:
1) It seems to come and go. On one machine I had it from the beginning, uninstalled Fork and reinstalled, and it went away. On another, it was working fine and then stopped working. In both cases it's as above - works fine from the command line, only fails from within Fork UI.

2) It's not so easy to work around in my case, because I'm using the config file to specify what ssh key to use.

**Comment by DanPristupov** [comment]
@AndrewGodfrey 
1. Ensure that Fork uses Default System Settings in SSH configuration.
2. Ensure that Fork uses the same git instance as command line.

**Comment by AndrewGodfrey** [comment]
Thank you! This fixed it. I think Fork UI could be improved: The "Configure SSH Keys" dialog would better be named "Select an SSH key". The current name gives the impression that Fork supports the use of multiple SSH keys through that dialog, but only the "Default system configuration" does.

I am aware that the subtext on that dialog speaks to this ("1. Select or generate a new ssh key which will identify your computer") - i.e. Fork's mental model is that you only need one SSH key per computer. But that detail was hard to notice. So, I had selected a different key under the mistaken impression that the dropdown is just a weird way to view the list of keys.

**Comment by karladler** [comment]
> Ensure that Fork uses Default System Settings in SSH configuration.
> Ensure that Fork uses the same git instance as command line.

Mind that the first one is reached by NOT selecting any SSH key in the SSH-Config menu.

**Comment by decadence** [comment]
@DanPristupov 
I'm a bit confused. What happens if I select multiple SSH Keys in Fork? It uses first valid key or what? I can't change order of this keys or delete generated key (only deselect key). Can't find any documentation about it.

**Comment by DanPristupov** [comment]
@decadence fork will simply pass multiple `-i /path/to/ssh/key` arguments to SSH (https://www.ssh.com/academy/ssh/command#ssh-command-line-options)

You can't delete a generated key because I don't wan't Fork to have a code which removes ssh keys. Just so I could sleep better  :). So, you must open `~/.ssh` in file manager and remove the keys manually.

**Comment by mucco** [comment]
>     1. Ensure that Fork uses Default System Settings in SSH configuration.
> 
>     2. Ensure that Fork uses the same git instance as command line.

Thank you, number 2 was the solution for me
