### ISSUE TITLE
Git for Windows 2.19

### ISSUE THREAD

**Issue by beppler** [ForkIssues/TrackerWin#50]
The current version of Fork is using portable Git 2.19.1.

This version of Git for Windows include Git Credential Manager v1.18.0 that has this [a bug](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/774).

Updating to Git 2.20.0 (release candidate) or updating Git Credential Manager to 1.18.3 solves the problem.

**Comment by DanPristupov** [comment]
Should be solved in 1.24

**Comment by SDohle** [comment]
Hi,

doesn't work in 1.24 for me :(

**Comment by DanPristupov** [comment]
@SDohle any details?

What exactly doesn't work?
What errors?

Do you have the "NullReference" exception on fetch?

**Comment by SDohle** [comment]
Hi,

fork is in version 1.24.0.0 with git version 2.19.2.windows.1. On clone, fetch, pull, push i get:

> fatal: Authentication failed for 'https:tfs-git-url-to-repository  error: Could not fetch origin

OS is Windows 10 and we authenticate against a Team Foundation Server with empty username & passwords so that git uses the active windows credentials.

With the system wide installed git version 2.17.1.windows.2 or a fork 1.21 this setups works fine.

**Comment by DanPristupov** [comment]
I heard about same issue with TFS and some users reported that they solved it with the following command
`git config --system http.sslbackend schannel`

I can't test it myself because I don't have an access to TFS.

Upd: Probably some details: https://developercommunity.visualstudio.com/comments/269757/view.html

**Comment by SDohle** [comment]
Awesome! thank you very much!

That helps:
> `git config --system http.sslbackend schannel`

Is it possible to get the error output in fork more verbose?

**Comment by DanPristupov** [comment]
I don't think so. It shows full output git returned (both output and error streams).

Actually I'm quite amazed that Git for Windows (with a company of Git Credential Manager by MS) managed to break authentication 5 times during this year! This never happened to me on Mac.

**Comment by ghost** [comment]
Hi Dan,
We have the same issue and that's not ideal to have to enter this command in the Git used by Fork. I wish there was an option like on MacOS to choose the Git we want to use instead of the pre-installed one. Either by choosing a path to Git or even just checking if there is a git.exe available in the PATH. All ours devs have Git installed in their system and many also use the command line. This also avoid problem like this by having a controlled Git version independent from Fork.
I am not sure it's related to this one https://github.com/ForkIssues/TrackerWin/issues/25 or if I should create a new issue?

**Comment by DanPristupov** [comment]
@maxime-viargues-serato create a separate one, please.

**Comment by ghost** [comment]
Done thanks https://github.com/ForkIssues/TrackerWin/issues/86
