### ISSUE TITLE
Some View Mode options are not kept after restart

### ISSUE THREAD

**Issue by sglienke** [ForkIssues/TrackerWin#501]
While Fork remembers the first option (which of the 3 ways files should be displayed) it does not for the two bottom ones ("Hide untracked files" and "Show ignored files"). Both are back to False after restart.

**Comment by sglienke** [comment]
@DanPristupov Any chance to get this fixed any time soon?

**Comment by JulienMaille** [comment]
I second that request, "Hide untracked" should stick when restarting Fork.

**Comment by DanPristupov** [comment]
The problem is more complex than it sounds. Should these settings be remembered globally or per repository?

**Comment by JulienMaille** [comment]
I could live with a global setting (would be better than nothing).

**Comment by DanPristupov** [comment]
Well, it in this way after restart user will not see new files. Such behavior can be very confusing.

**Comment by JulienMaille** [comment]
Why would I be confused if I decided to check the "hide untracked" option? It's not the default setting, so I don't see any issue here.

**Comment by DanPristupov** [comment]
Hi. Could you tell, why do you hide untracked files in the first place?

**Comment by JulienMaille** [comment]
This is mostly for 3rd party repository with bad .gitignore configuration

**Comment by DanPristupov** [comment]
@JulienMaille The `.git/info/exclude` file has the same format as any `.gitignore` file. Could it be a solution for you? https://git-scm.com/docs/gitignore#_description

**Comment by andersmelander** [comment]
Please do something about this.
The only time I ever want to view untracked files is when I add files to a repository, so it's pretty annoying having to check "Hide Untracked Files" all the time.

See also #1802

**Comment by ian-h-chamberlain** [comment]
Personally I would love to have this option persist on a per-repo. I normally like to see untracked files in Fork but I also use it with my [`yadm`](https://yadm.io/) dotfiles repo, which by default shows my entire home directory as untracked files (obviously not very helpful!). I have to check "Hide untracked files" every time I open my dotfiles in Fork, which is fine but slightly inconvenient.

`yadm` sets this in the repo configuration so that `yadm status` doesn't show all the untracked files:

```gitconfig
[status]
	showUntrackedFiles = no
```
Perhaps Fork could default to following that configuration (which can be global or per-repo). I'm not sure whether it also makes sense to _modify_ the configuration (should it be global or per-repo?) when checking/unchecking "Hide untracked files", but at least this would give users a way to manually specify it and also get the same behavior in their `git` command line. I suppose if people want a different behavior between Fork and `git` that could pose a problem...

Edit: oops, I realized after I posted this that this is the windows tracker, but this feature was also requested on macOS with similar discussion about `status.showUntrackedFiles`: https://github.com/fork-dev/Tracker/issues/471

**Comment by parmentelat** [comment]
personally I am growing sick and tired of having to click this "hide untracked files" setting over and over again, I wish I would earn one cent each time, I'd be millionaire by now ;)

**Comment by DanPristupov** [comment]
> personally I am growing sick and tired of having to click this "hide untracked files" setting over and over again, I wish I would earn one cent each time, I'd be millionaire by now ;)

Thank you for reminding. We made Fork remember the 'Hide untracked files' setting in Fork 2.0 update. Please check for updates (File -> Check for updates).

**Comment by parmentelat** [comment]
Hey
thanks for the update
but actually I am running 2.45.2 and I still need to set this setting manually each time I restart Fork or I open a folder
what else can be wrong in my setup ?

<img width="362" alt="image" src="https://github.com/user-attachments/assets/38b6795d-921f-4e54-a46d-f932df605dd8">

**Comment by DanPristupov** [comment]
@parmentelat well, you are on Mac.

**Comment by parmentelat** [comment]
Well, yes, and ?

**Comment by DanPristupov** [comment]
This is the issue tracker for the Windows version.
