### ISSUE TITLE
[Feature Request] Allow to pass arguments to preferred shell

### ISSUE THREAD

**Issue by mloskot** [ForkIssues/TrackerWin#504]
It would be nice to be able to run Git Bash with e.g. `--login` to get  `.bash_profile` executed.

Currently, there is no way to pass any command line arguments to selected shell program:

![image](https://user-images.githubusercontent.com/80741/67084500-63522c80-f19d-11e9-8e7f-a87b175a9dfa.png)

**Comment by Otiel** [comment]
I would also like to be able to pass arguments to the specified shell as well. I'm using [cmder](https://cmder.net) with several arguments.

For those interested, here is the workaround I currently use:
1. Create a _bat_ file to start the shell with args specified.
2. Use a program to transform the _bat_ file into an _exe_ file (because Fork doesn't allow _bat_ files as a custom shell path).
3. Set the custom shell path in Fork to be the _exe_ file.

In my case:
1. _bat_ file contents:
```
@echo off
set CMDER_ROOT=%~dp0

start %CMDER_ROOT%\vendor\conemu-maximus5\ConEmu.exe /Icon "%CMDER_ROOT%\cmder.exe" /Title Cmder /LoadCfgFile "%CMDER_ROOT%\config\ConEmu.xml" /Reuse %~1
```
2. I used a program called `Bat To Exe Converter` to convert the _bat_ file to an _exe_ file.
3. Finally, reference the _exe_ file in Fork as custom shell:
![image](https://user-images.githubusercontent.com/3851902/69523478-45c66e80-0f64-11ea-98d7-c50ff03efc64.png)

**Comment by jlieuw** [comment]
I would also like the feature to pass arguments to the windows terminal since that's possible in microsoft/terminal/pull/4023

**Comment by andrewskirrow** [comment]
This would be especially useful to allow picking the desired shell when using the new windows terminal. At the moment it just picks the "default" windows terminal shell.

**Comment by DanPristupov** [comment]
@andrewskirrow the new terminal should also be recognized if it's located at `%localappdata%\Microsoft\WindowsApps\wt.exe`
