### ISSUE TITLE
Use a static color for the "default" branches

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#532]
In addition to using a different order for branch colors (#308), I think using a static color (= always the same color, no matter the repository or the branch depth in the graph) for the "default" branches would help navigating into the commits and instantly notice those branches.

By "default" branches, I mean those branches most of us always have in our repository:
* `master`
* `develop` or `dev`

**Comment by DanPristupov** [comment]
May be I'm missing something but I think it's conceptually wrong to say 'branch color'. Branches in git are just labels/pointers. They are not related to the commit graph and to the lines you see on the display.

Basically you asked to color 99% lines in commit graph with the same color (because 99% of commits belong to the master branch).

**Comment by Otiel** [comment]
>They are not related to the commit graph and to the lines you see on the display.

Right, bad wording from my part. I meant to display the graph line with a static color if the line is linked to a branch which name matches `master` or `dev`.

Branches names (on those chips ![image](https://user-images.githubusercontent.com/3851902/68199778-f2917980-ffbe-11e9-82e0-67dbbcf347ae.png)) are displayed with the same color as the graph line, so the contrary should be possible, no?

**Comment by DanPristupov** [comment]
Look at the following screenshot. Should we draw all lines there with the orange color? Both lines are `develop`.

<img width="476" alt="Screenshot 2019-11-05 at 11 38 05" src="https://user-images.githubusercontent.com/618115/68200733-bfe88080-ffc0-11e9-8d1a-002dd7d7c525.png">

**Comment by Otiel** [comment]
>Should we draw all lines there with the orange color?

No, only the left line.

(not sure if this is a real question or a way to make me understand that what I'm asking is _wrong_?)

**Comment by DanPristupov** [comment]
> (not sure if this is a real question or a way to make me understand that what I'm asking is wrong?)

I always look forward to improve the design and this is the real question. However I suppose that there's misunderstanding on your side.

1. All the commits on the example belong to the develop branch. Because 'develop' is just a **named commit pointer** to the 'Fix User Timing...' commit. Think about a file shortcut in Windows.
2. The merge commit is just a commit with 2 parents. It doesn't contain any information about branches.
3. Furthermore, the commits (and the whole commit graph !) don't know about branches.
4. Instead branches know about commits they point to. You can easily move branches from their point to any other point using the 'Reset branch' option.

> No, only the left line.

But why? Do you think `develop` was there one day? We can't be sure about that. It could also be on the right line.

P.S. There can be a slightly worse case. 
<img width="128" alt="Screenshot 2019-11-05 at 14 07 29" src="https://user-images.githubusercontent.com/618115/68210352-9f76f100-ffd5-11e9-8018-77b42826fad2.png">

**Comment by Otiel** [comment]
> 1. ...
> 2. ...
> 3. ...
> 4. ...

Yes, I understand all that.

> But why? Do you think `develop` was there one day? We can't be sure about that. It could also be on the right line.

I agree.

Let me ask you the contrary: on your [example](https://github.com/ForkIssues/TrackerWin/issues/532#issuecomment-549767335) why is the `develop` chip painted orange, and the whole left line as well?

**Comment by DanPristupov** [comment]
The label takes the color of the line it belongs to.

The line color is defined as `colors[lineId%color.count]`. The colorizer starts from the top and goes down commit by commit. Each time a merge commit encountered, a new line (with a new id) appears.

**Comment by Otiel** [comment]
> The label takes the color of the line it belongs to.

So on the graph, there _is_ a relation between the label (branch name in our case) and the painted line.

Let me start again my request from scratch:

1. Always paint the `develop` label orange, and the `master` label green.
2. When painting a line, if the `develop` label belong to this line, paint the line orange. If the `master` label belong to this line, paint the line green.

Does it make more sense?

**Comment by bergamin** [comment]
Guys, I know this issue has been closed already. I just want to suggest a work around (not intended to reopening the issue):

Fork has the option to collapse merges. If you work with Gitflow, collapse everything and then expand only merges into develop originated from feature branches. You will only need to see those commits anyway in a daily basis. Only expand release branch originated merges if you really need to see something there and then collapse them again.

Now you have a consistent line for develop and master.
