### ISSUE TITLE
Git Flow form shows incorrect prefix

### ISSUE THREAD

**Issue by mttpg** [ForkIssues/TrackerWin#579]
If custom prefixes are set in the git config file (initialised through Fork) it doesn't show the custom prefix in the Start Feature form. It always shows the default option instead (but when the branch is created it does use the custom prefix).

**Comment by DanPristupov** [comment]
Do you mean the labels are incorrect?

**Comment by mttpg** [comment]
Yes, the label in the "Start git flow feature" form that says "feature/" before the input box does not reflect the git flow config. It's confusing because you don't know until you've clicked OK whether the software will create the branch according to the custom naming scheme or not.

**Comment by aenikata** [comment]
I can confirm I'm seeing the same behaviour - I have git flow configured to use 'workitem' as the prefix folder, but it says 'feature/' instead of 'workitem/' before the input box. When you click OK and a label shows what branch is being created the correct branch is shown then (and the correct branch is created).

This is in the Fork for Windows v1.43.3.0

**Comment by DanPristupov** [comment]
The prefix labels should be fixed in Fork 1.45
