### ISSUE TITLE
GitHub user picture (avatar)

### ISSUE THREAD

**Issue by tibel** [ForkIssues/TrackerWin#594]
Additionally to gravatar it would be great if Fork could support GitHub user pictures.

Especially when when using "Keep my email addresses private" in your GitHub account.
Then you have an email address like the following:
`<username>@users.noreply.github.com`

See also
https://stackoverflow.com/questions/22932422/get-github-avatar-from-email-or-name

**Comment by drothmaler** [comment]
also for the Mac version please...

**Comment by falkenhawk** [comment]
@DanPristupov user avatar can be easily retrieved from github with URL `https://github.com/<username>.png`
https://github.com/DanPristupov.png

**Comment by DanPristupov** [comment]
@falkenhawk github username is not related to git username.

**Comment by falkenhawk** [comment]
@DanPristupov that's correct, but this ticket is about the specific case where "private" github email address (in format of id+username@users.noreply.github.com) is used in git commits. Gravatar can't be configured for such emails because it sends out a validation link to the email, but github simply rejects all emails sent to "private" addresses.

Instead, Fork could possibly catch such emails in commits with a regex and fetch an avatar directly from github. 💡
Similarly to e.g. https://github.com/atom/github/pull/1483/files

**Comment by DanPristupov** [comment]
@falkenhawk I see now. Yes, you are right. Thank you!

**Comment by tibel** [comment]
v1.57 :heart: thanks
