### ISSUE TITLE
Repository Not Found

### ISSUE THREAD

**Issue by jamesbuckley1** [ForkIssues/TrackerWin#596]
Cannot open any repositories after updating to 1.42.6
The message remains the same "Repository Not Found. Repository deleted or moved".

I can open each repo in Windows explorer.
Using the installed gitInstance, I can access all my repos.

**Comment by DanPristupov** [comment]
Hi. Looks like the git upgrade went wrong. Please download https://git-fork.com/update/win/ForkInstaller.exe and reinstall the app.

**Comment by DanPristupov** [comment]
It's very difficult to upgrade git instance on remote computers. It seems to be trivial on first sight (just extract 7z archive), but in reality there could be many unexpected problems (like Windows Defender denying to extract git.exe because it's an executable file).

Looks like I need to validate the git instance after the upgrade and show a detailed error if it fails + ability to 'try again'.

**Comment by jamesbuckley1** [comment]
Reinstalling resolved the issue. Thanks a lot!

**Comment by DanPristupov** [comment]
Sorry for the inconvenience. I'll do my best to make the next git upgrade flawless.
