### ISSUE TITLE
Selecting nested tag does not select corresponding commit

### ISSUE THREAD

**Issue by markovicpp** [ForkIssues/TrackerWin#626]
When a tag is created as nested tag, then clicking on the tag name in the tag list does not select linked commit in the commit list.

**Steps to reproduce:**

1. Open command line in a repository
2. git tag -a abc -m "abc"
3. git tag -a def -m "def" abc
4. Click on "def" tag in Fork

**Expected result:**
Commit with "abd" and "def" tag is selected

**Actual results:**
No change in commit selection

**Notes:**
This kind of tags are created by TFS
git version 2.23 and later now displays following message
```
hint: You have created a nested tag. The object referred to by your new tag is
hint: already a tag. If you meant to tag the object that it points to, use:
hint:
hint:   git tag -f def abc^{}
```
This message was not displayed in v2.21

**Fork version:**
Mac 1.0.88
Windows 1.43.3.0

**Comment by DanPristupov** [comment]
Sorry, I moved the issue to the Windows tracker, but just noticed that you mentioned both versions.

So, regarding the problem. I didn't know about that feature.

```
$ git rev-parse HEAD
4416f7f24250250baf7d2fee8d8d7d3e4658c581 <-- this is our HEAD
$ git tag -a test/xxx -m "xxx"
$ git tag -a test/yyy -m "yyy" test/xxx
$ git for-each-ref refs/tags/test --format='%(objectname) %(refname) %(*objectname)'
95524ec4251fe19928c8ec3c213da18f58e7657f refs/tags/test/xxx 4416f7f24250250baf7d2fee8d8d7d3e4658c581 <-- HEAD
ed823a97f91378a8e30b71ace39743faa37c007e refs/tags/test/yyy 95524ec4251fe19928c8ec3c213da18f58e7657f <-- xxx
```

It looks like the second object points to the first object (a double pointer). YYY -> XXX -> SHA
I couldn't find a way to dereference an object twice:

```
$ git for-each-ref refs/tags/test --format='%(objectname) %(refname) %(*objectname) %(**objectname)'
fatal: unknown field name: **objectname
```

In theory we could handle such cases runtime but it will require to iterate through all tags and check whether each tag points to some other tag which is O(n^2) or O(n). This can be a large performance slow down for some repos with A LOT of tags (e.g. ~15000 in Chromium).

I will figure out, however I suppose this problem will not be fixed in Fork in the near future.

What is the use case for such objects, btw?

**Comment by pavolmarkovic-serato** [comment]
Hi Dan, thanks for looking into this.

I wasn't aware of this issue at all until recently when this kind of nested tag had been created through Microsoft TFS web interface.

I forgot to mention that those nested tags are not displayed in the commit list as well (but that's probably what you mention as your main performance concern).

Seems `git log` does the derefencing

```
$ git log --format='%H' test/yyy
4416f7f24250250baf7d2fee8d8d7d3e4658c581

git log --format='%D' 4416f7f24250250baf7d2fee8d8d7d3e4658c581
tag text/yyy, tag test/xxx
```

I really don't know what's the use case, I thought that maybe if the tag referencing the commit would be deleted then all tags referencing the tag would be deleted as well. But that's not the case, the indirect tag still references the deleted tag and shows in the log.

This issue is not a priority, rather than letting you know that this kind of scenario exists.

Btw. that hint about nested tags was introduced in git v2.22: https://github.com/git/git/commit/eea9c1e78ffd878cbaaf2c1e346e186a1e58a460

**Comment by markovicpp** [comment]
Hi Dan, thanks for looking into this.

I wasn't aware of this issue at all until recently when this kind of nested tag had been created through Microsoft TFS web interface.

I forgot to mention that those nested tags are not displayed in the commit list as well (but that's probably what you mention as your main performance concern).

Seems `git log` does the derefencing

```
$ git log --format='%H' test/yyy
4416f7f24250250baf7d2fee8d8d7d3e4658c581

$ git log --format='%D' 4416f7f24250250baf7d2fee8d8d7d3e4658c581
tag text/yyy, tag test/xxx
```
> What is the use case for such objects, btw?

I really don't know what's the use case, I thought that maybe if the tag referencing the commit would be deleted then all tags referencing the tag would be deleted as well. But that's not the case, the indirect tag still references the deleted tag and shows in the log.

This issue is not a priority, rather than letting you know that this kind of scenario exists.

Btw. that hint about nested tags was introduced in git v2.22: https://github.com/git/git/commit/eea9c1e78ffd878cbaaf2c1e346e186a1e58a460
