### ISSUE TITLE
Putty SSH keys converted to OpenSSH format

### ISSUE THREAD

**Issue by Toto1411** [ForkIssues/TrackerWin#631]
Hello,
could it be that Fork does not handle encrypted keys correctly? It recognizes my key configured for git bash on Windows but outputs the following error on push without prompting for the password:
"load pubkey "[...]/.ssh/id_rsa": invalid format
me@machine: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by DanPristupov** [comment]
What is encrypted key? I can't find any info. https://duckduckgo.com/?q=ssh+generate+encrypted+key&t=osx&ia=web

UPD: Do you mean a key with a passphrase? They should be handled properly.

Did you select your key in the SSH configuration in Fork?

**Comment by Toto1411** [comment]
Thank you for the fast answer. Yes, I mean a key with a passphrase. Sorry if I didn’t use the right words. The key is selected in the configuration but I’m not asked for the passphrase.

**Comment by DanPristupov** [comment]
It's possible that you entered a wrong password and Fork memorized it. Try to open Credential Manager application (it's located in the Windows start menu) and remove the key `fork:/path/to/your/key`. Then fetch again.

**Comment by Toto1411** [comment]
Okay, I deleted the password and entered it again as fork asked for it. Still the same message: `"C:/Users/[myname]/.ssh/id_rsa": invalid format`. Tried it multiple times to be sure I didn't misspell. The password works in git bash. There the same error is showing up, then git asks me for the password and it works.

**Comment by DanPristupov** [comment]
OK. Could you send the log file to my email (winsupport@forkapp.io) please? `%localappdata%\fork\logs\fork.log`

**Comment by DanPristupov** [comment]
For other people having same problem, here's what we've found:

> I created the key during the first start assistant in TortoiseGit using TortoiseGitPlink to generate the PuTTY key pair (ssh-rsa 2048 Bit). As I became more used to Git I converted the key from the .ppk format to the OpenSSH format with the PuTTY Key Generator. I didn’t think this would be a problem as it works in the bash.

I never tried this approach, so I need to investigate this way. As for now I'd recommend to generate a new key (either in Fork or in [command line](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)).

**Comment by Toto1411** [comment]
Another working alternative is to run Pagent with the ppk key file and the environment variable GIT_SSH set as suggested [here](https://github.com/ForkIssues/TrackerWin/issues/179#issuecomment-468584409).

**Comment by ThomasFOG** [comment]
Same issue here. I can't get a 2048bit passphrase protected key to work with Fork on Windows.

It was generated using puttygen, and is a key I regularly use with several kind of ssh clients without issues (being openssh, or putty).

I exported an openssh version of it for Fork (which I assume is the format Fork's expecting since it reads my public openssh key properly and gets its fingerprint).

When fetching repo's, Fork doesn't ask for the passphrase, but instead tries to log into ssh with a password (and therefore asks me a login/password for the ssh user I'm trying to use while it shouldn't).

It then fails with the "invalid format" message on the private key.

Looking into Fork's log files, it looks to be related to parsing the key:
```
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Fork.UI.Dialogs.SshKeyItem.GenerateFingerprint(SshKey sshKey)
```

On one occurrence, Fork asked me for the passphrase, and then never asked me again despite trying to generate another (passphrase protected) key and providing it.

I've tried reinstall Fork in case it was about a stale config file, but it appears that something is still kept somewhere since even after reinstalling it never asked me for the passphrase again.

EDIT: I ended up using this as a pretext to renew my rsa ids. Generated 4096bit keys with openssh and things went smoothly now.

**Comment by DanPristupov** [comment]
> On one occurrence, Fork asked me for the passphrase, and then never asked me again despite trying to generate another (passphrase protected) key and providing it.

Fork stores credentials (including passphrases for SSH keys) in Windows Credential Manager. You can find this application in the Windows Start menu.

**Comment by ThomasFOG** [comment]
Thanks, Dan. Convenient.
Things went smoothly once I used ```ssh-keygen``` instead of ```puttygen```. Putty is likely doing something shady with file encoding.
