### ISSUE TITLE
Create Tag with keyboard shortcut

### ISSUE THREAD

**Issue by RalfKoch** [ForkIssues/TrackerWin#665]
in the view "All Commits" select a commit and with the right mouse click command "Create New Tag" you can create a new tag for that commit. That works fine.
Now select another commit [branch does not matter] in the tree and use the keyboard shortcut "Ctrl + Shift + T" and enter the new tag in the dialog. Click "Create Tag" and the new tag will be save, but it will not be applied to the currently selected commit but to the top commit of the currently active branch.

I guess this is not by design, is it?

**Comment by DanPristupov** [comment]
This is an intentional behavior. Branch and tags called by shortcuts are created on HEAD.

Tag and branch git commands are logically coupled with the active commit (HEAD).

- a straightforward command `git tag test` creates tag on HEAD
- creating tag on other place requires explicit command `git tag test SHA`

Fork uses a similar behavior:
- an easy-accessible command creates tag on HEAD
- creating tag on a specific place requires explicit action

**Comment by RalfKoch** [comment]
OK, copy that.
Thanks

**Comment by RalfKoch** [comment]
OK, copy that.
Thanks.
