### ISSUE TITLE
[Feature request] I would add parameter for custom shell

### ISSUE THREAD

**Issue by PatrceBrunelleCimel** [ForkIssues/TrackerWin#703]
In File --> preferences --> integration, we can add arguments to merge and diff tool but not to the shell.
Maybe add environment variable should be a nice feature when you launch an external tool too.

I try to launch mintty.exe of Cygwin but if I don't add a dash '-' in argument, that doesn't work because a login shell is not launched.

PS: I tried to add arguments in settings.json as diff and merge tool but it doesn't work

**Comment by DanPristupov** [comment]
There is a quite similar issue already here: https://github.com/ForkIssues/TrackerWin/issues/504.

However I think we can add custom parameters for custom shell much easier than for all shells, so I'll keep this one open.

**Comment by DanPristupov** [comment]
1.0.47 is out. Please check if works as you expected.

**Comment by PatrceBrunelleCimel** [comment]
That works !
Thank you

**Comment by BrainCrumbz** [comment]
Hi. Sorry to resume an older thread. But how do you actually pass a parameter to custom shell? We were not able to figure that out by looking through the various referenced issues.

In our case, we'd like to integrate Cmder as a shell. In order to launch Cmder, the command line should be something like:

```
"C:\Program Files (x86)\cmder\Cmder.exe" /start <PASS PATH HERE>
```

In the context of shell integration, we thus have:

* Shell: `Custom`
* Shell Path: `C:\Program Files (x86)\cmder\Cmder.exe`
* Arguments: `/start ??????`

How do we pass the current repository path in the *Arguments* form field?

TA

**Comment by Otiel** [comment]
@BrainCrumbz Did you try what I suggested [here](https://github.com/fork-dev/TrackerWin/issues/504#issuecomment-558042350)?

**Comment by BrainCrumbz** [comment]
@Otiel thanks for quick reply. I think that scenario does not work for our needs, but maybe we're wrong. Please let me explain why.

It seems to me that your solution works when you want to pass a known, fixed "value" to your shell program. Thus, you create a batch file where that fixed value is present, then convert the batch file into an executable. In such executable, the passed value is "baked in".

In our case, there's no known, fixed value to pass to our shell program. We need some placeholder token provided by Fork, say e.g.  `$CURRENT_PATH`, so that we can fill the *Arguments* field as:

`/start $CURRENT_PATH`

Then, when one chooses `Open in Console` button, Fork should at that moment replace the placeholder (`$CURRENT_PATH`) with the actual path of current repository, and launch our shell program with the resulting command line arguments. It cannot be baked in a pre-made exe.

Does that help in explaining what we're looking for?

**Comment by PatrceBrunelleCimel** [comment]
I have this on my side with Cygwin and that works

![image](https://user-images.githubusercontent.com/60889440/156418642-24f77074-f5f0-43c3-88fa-0d94bffd8e00.png)

**Comment by BrainCrumbz** [comment]
@PatrceBrunelleCimel how can we pass, in *Arguments* field, the root path of current repository?

In the sense: `"Fork Shell"`, `/Cygwin-Terminal.ico`, `"C:\Soft\test.log"`, those are all *fixed* values with respect to the current repository. That is, those are known, set once for all, and you can thus stuck them into that *Arguments* field.

But in order to open Cmder in root path of current repository, we need some placeholder token. Similar to the External Diff Tool section, where you have `$REMOTE` and `$LOCAL` tokens which will be replaced by Fork with the actual file paths.

**Comment by PatrceBrunelleCimel** [comment]
Ha ok. I see what you want and I don't know how do that.
I've tried to open the custom terminal in the directory of the current git repository 2 years ago without success.

**Comment by Otiel** [comment]
@BrainCrumbz I'm a bit rusted regarding the script I posted [here](https://github.com/fork-dev/TrackerWin/issues/504#issuecomment-558042350) as I'm using Windows Terminal in favor of Cmder now, but I just tried it and it does open Cmder in the current repository.

**Comment by BrainCrumbz** [comment]
@Otiel the screenshot found at that comment is "cut" (link [here](https://user-images.githubusercontent.com/3851902/69523478-45c66e80-0f64-11ea-98d7-c50ff03efc64.png)), we cannot see what's in the *Arguments* field. What did you pass in there at that time?

**Comment by BrainCrumbz** [comment]
Ok, whatever. It works when passing NO ARGUMENT whatsoever (i.e. not even `/start`).

![immagine](https://user-images.githubusercontent.com/3185573/156424357-4b1ad7c5-6ca7-4872-8382-bc8a09210e42.png)

🤷🏽🤷🏽🤷🏽

**Comment by Otiel** [comment]
The screenshot is not truncated, there simply was no argument field at that time. 😆

I'm not sure _why_ it works without passing any argument, maybe the working folder is set to the repository path? @DanPristupov

**Comment by matt77hias** [comment]
@BrainCrumbz  Hey, how did you manage to integrate Cmder in Fork? Without passing any explicit directory variable, Cmder.exe just starts in its default directory which is independent of the git repository being used.

**Comment by DanPristupov** [comment]
@matt77hias Fork passes repository path as working directory. So, it should work, until you specified a default start directory somewhere.

**Comment by matt77hias** [comment]
@DanPristupov but how does Fork pass the repository path to a custom shell? The way of passing such argument varies across shells (_e.g., Cmder uses a `/Start` argument_).

Or does Fork actually launch the custom shell from within the repository path instead? I assume that could work for some shells, but Cmder is actually a program that launches shell(s) itself.

**Comment by DanPristupov** [comment]
> Or does Fork actually launch the custom shell from within the repository path instead?

Yes, it's called working directory and it is part of OS API.

> I assume that could work for some shells, but Cmder is actually a program that launches shell(s) itself.

I suppose it must handle the working directory. At least that's what other users say: https://github.com/cmderdev/cmder/issues/57#issuecomment-453833112, https://github.com/cmderdev/cmder/issues/57#issuecomment-480269525

**Comment by matt77hias** [comment]
Thank you for clarifying @DanPristupov. It is indeed a configuration of Cmder itself instead of Fork.

If someone has the same issue with Cmder (and Bash), for [reference](https://superuser.com/a/1329474/432569):
![Cmder](https://github.com/fork-dev/TrackerWin/assets/2464019/d0baec40-6d97-4ec7-a2cc-366233afaf38)

Works like a charm now in Fork 🎉

**Comment by BrainCrumbz** [comment]
> @BrainCrumbz Hey, how did you manage to integrate Cmder in Fork? Without passing any explicit directory variable, Cmder.exe just starts in its default directory which is independent of the git repository being used.

Hi @matt77hias . At that time, we were able to integrate Cmder in the way shown at this reply above: https://github.com/fork-dev/TrackerWin/issues/703#issuecomment-1057241991

At the moment we're not using Cmder anymore with Fork. Just as an example, at the moment we integrated Windows Terminal and that works with this settings (though I think that was already included in Fork available options):

> Shell: WindowsTerminal
> Shell Path: C:\Users\xxxxx\AppData\Local\Microsoft\WindowsApps\wt.exe
> Arguments: -d .

![immagine](https://github.com/fork-dev/TrackerWin/assets/3185573/699bc6ed-1e6a-4df9-8c65-96d290457806)
