### ISSUE TITLE
Bigger fetch/push/pull buttons - also with text and number of commits for push/pull

### ISSUE THREAD

**Issue by DarkDeny** [ForkIssues/TrackerWin#72]
It is very usefull in SourceTree:
1. having a big buttons with also text under them (it is not that intuitive for me to figure out which arrow does what)
2. When Push and Pull buttons are big, they should show a number of commits to be pushed/pulled

**Comment by DanPristupov** [comment]
1. As for now we don't have plans to add titles. I think showing the tooltips is enough.
2. I'll think about that. I need to make a mockup first, not sure if such small digits will be visible.
3. There's an option to push on commit in the commit button dropdown.

P.S. Generally creating issues with multiple proposals is a quite bad practice. I don't know when I can close them and also other people cannot vote, which is even worse because my todo list is driven by feature requests.

**Comment by DarkDeny** [comment]
Well, bad for me. I really lose time hovering all these arrows to figure out which one to click =(.

**Comment by DarkDeny** [comment]
P.S. I removed third comment which was not directly relater to big buttons.

**Comment by nitpum** [comment]
Please add titles and number of commits to be push/pull/fetch. like @DarkDeny says it not intuitive what arrow does (Maybe should change the icons).  I think number of commits is really important. I can know that have new commits to pull or how many commit that haven't pushed yet.

**Comment by DanPristupov** [comment]
We will check a possibility to add titles to buttons.

> I can know that have new commits to pull or how many commit that haven't pushed yet.

The behind/ahead information is displayed in the status control:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/618115/51239776-83d52800-197a-11e9-9893-85d77b073683.png">

**Comment by DanPristupov** [comment]
In 1.27 we added labels to the buttons.
