### ISSUE TITLE
[Feature Request] Custom Commands

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#843]
Hi,
We would like to extend Fork to allow us creating GitLab-Merge-Requests directly from Fork using the [Gitlab API](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/merge_requests.md#create-mr).

So, it would be awesome if there would be a button opening a dropdown which allows you to select a custom command or add a new custom command for the current repository (optionally also globally).

when adding a new command the user should be able to give a name to the command and link a text file with the commands to perform (alternatively an input field).

would be great if there can be placeholder values which are replaced by fork, like %current_branch% or %project_url%.

**Comment by JeReT** [comment]
Here is a mockup, how it could be integrated into the UI:

![custom_commands](https://user-images.githubusercontent.com/530561/86593545-bb33fc00-bf95-11ea-8c4f-f0d9f7cebabd.png)

Edit:
I found a "Custom Commands" section in the preferences but I have no clue how to use it... Is it already what I am asking for?

**Comment by Otiel** [comment]
>Is it already what I am asking for?

I believe you can perform what you're asking with the existing Custom Commands.

There are currently four types of Custom Commands. In order to access a Custom Command, the process depends on its type:
* Commit : right-click on a commit
* Repository : click on "Open in" button
* File : right-click on a file (in Changes or File Tree tabs for instance)
* Branch : right-click on a branch (on the sidebar)

For each type, there are a number of placeholders available (displayed when you create a Custom Command). For instance, if you create a new Branch Custom Command, the `$name` placeholder references the selected branch name.
