### ISSUE TITLE
[Feedback] New search makes the left pane a bit too busy

### ISSUE THREAD

**Issue by tihomir-kit** [ForkIssues/TrackerWin#882]
Hi, I just wanted to leave a tiny bit of feedback on the recent change regarding the left pane. I'm not sure sure how it could be improved, but I feel that the left section is now a bit too busy and the UX feels slightly confusing:

![image](https://user-images.githubusercontent.com/535842/88056412-66c57a80-cb58-11ea-9cde-6a734bc96f36.png)

I think that the bar that has the branch and search icons does not make a clear separation between "Changes / All Commits" and it doesn't communicate clearly enough that the branch/search are basically tabs, so it feels a bit weird to use. 

Perhaps if there was a bit of bottom padding below "All commits" to make it clear that "Changes" / "All commits" relate to the main right pane. 

And the second thing that comes to mind would be to not use the blue color to highlight branch or search but to make them buttons kind of like "repository tabs" that can be used to switch between repos. And then you could highlight currently selected with lighter grey like with repo tabs. 

![image](https://user-images.githubusercontent.com/535842/88057074-74c7cb00-cb59-11ea-8d2e-cc3eb3be42e6.png)

If that makes sense..

Just throwing ideas around. I know this is subjective so feel free to close the issue if you don't like it.

**Comment by DanPristupov** [comment]
> I think that the bar that has the branch and search icons does not make a clear separation between "Changes / All Commits" and it doesn't communicate clearly enough that the branch/search are basically tabs, so it feels a bit weird to use.

Yes, I agree. Currently the sidebar is in in-progress state and some things can look weird.

There will be more tabs In the future:

<img width="370" alt="Screen Shot 2020-07-22 at 17 30 32" src="https://user-images.githubusercontent.com/618115/88196066-0e1ddc80-cc41-11ea-8251-ff10f3ba81ae.png">

> And the second thing that comes to mind would be to not use the blue color to highlight branch 

Personally I think the blue color looks fine there. May be because I already got used to it because I use the developer version with more tabs.

**Comment by imflyou** [comment]
That would be great if we could combine "Commit Message" and "Author" search conditions together!

**Comment by rgobo** [comment]
Agreed, it is a strange decision not to implement the filter above the main grid (where the search was previously) since there's plenty of space there, and there wouldn't be a need to duplicate commit lists. It is also impossible to tell on which branch the commit is when it is displayed on the left. Filtering by specific branch does not affect the new commit list, so in a way the newly implemented redundant commit list on the left is inferior to the one in the middle in terms of functionality.

And as PrintfAndScanf pointed out, it'd be great if we could chain conditions by simply typing something like "--author=userx --after=2020-07-01 --before=2020-07-29" rather than being restricted to just one condition at the time. I believe git log can even support regex search filters so you can filter by multiple authors if you want to.

I'm not sure in what way are commits filters implemented below the surface, but would adding a functionality to add custom filters be feasible? Something like setting custom commands in preferences, except for git log?

**Comment by Otiel** [comment]
>Agreed, it is a strange decision not to implement the filter above the main grid (where the search was previously) since there's plenty of space there, and there wouldn't be a need to duplicate commit lists. It is also impossible to tell on which branch the commit is when it is displayed on the left. Filtering by specific branch does not affect the new commit list, so in a way the newly implemented redundant commit list on the left is inferior to the one in the middle in terms of functionality.

I agree with most of this, but I would like to add that the new search adds some functionality that wasn't there before: the possibility to filter the list of commits.

**Comment by DanPristupov** [comment]
@Otiel ... and also see the list of file matches when searching by diff or file path.
<img width="255" alt="Screen Shot 2020-08-25 at 14 59 18" src="https://user-images.githubusercontent.com/618115/91177113-8f0a4100-e6e3-11ea-8c8f-667fb8cbd960.png">
