### ISSUE TITLE
Reorder custom commands

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#922]
I'd like to be able to reorder my Custom Commands from the Preferences window.

**Comment by DanPristupov** [comment]
There's no UI for this yet, but since Fork 1.54 you can reorder the corresponding entries manually in the `custom-commands.json` file.

There are 3 different locations: 
- `%localappdata%\Fork\custom-commands.json` - for global custom commands
- `.git\fork\custom-commands.json` - for private repository-wide custom commands
- `.fork\custom-commands.json` - for shared repository-wide custom commands

**Comment by markshep** [comment]
What's the path to the global custom commands on Mac?

**Comment by DanPristupov** [comment]
@markshep `~/Library/Application Support/com.DanPristupov.Fork/custom-commands.json`
