### ISSUE TITLE
[Bug] Crashing when writing commit message

### ISSUE THREAD

**Issue by Eyu-Tech** [ForkIssues/TrackerWin#975]
Hi,

nearly every time I write a commit message Fork crashes at least once.
This has been the case for many months and appears to become worse.

I don't recognize any pattern when crashing, it's completely arbitrary. But it's so frequent that I can "reproduce" the error.

Can I activate crash reports or send logs if there are any by default?

**Comment by DanPristupov** [comment]
Does this happen with the commit field only?

**Comment by DanPristupov** [comment]
> Can I activate crash reports or send logs if there are any by default?

I guess, no. This crash happens on a quite low level in some generic windows dll. The application gets killed without a signal. Even an active debugger doesn't catch it.

I just checked the source code, there's some suspicious code which may cause the problem somehow. I will reorganize that code and we'll see if that helps. But before I do this, could you confirm that only the commit subject field has a problem?

**Comment by Eyu-Tech** [comment]
Yes it only happens in the Commit field. It might also happen in the Subject field of the commit but I can't recall when it might have happend last.

Thanks for the quick response.

**Comment by DanPristupov** [comment]
Just to be clear. Does it happen when you type in the top (commit subject) or bottom one (commit description)?

<img width="780" alt="Screen Shot 2020-10-16 at 10 50 04" src="https://user-images.githubusercontent.com/618115/96237238-5aa55980-0f9d-11eb-878d-8124dadd3935.png">

**Comment by Eyu-Tech** [comment]
The bottom one.

**Comment by DanPristupov** [comment]
Ah, OK. It changes everything then.

I think I found the crash report. In it, the Fork source code is not in the call stack, it all happens within the UI framework.

The crash message says: `Requested distance is outside the content of the associated document`. So, the problem is caused by some incorrect distance calculation within the text control. Do you have any unusual UI settings in Windows? Custom DPI, increased fonts or classic theme may be?

**Comment by Eyu-Tech** [comment]
Nothing unusual.
I use UI Scaling when in Home Office. But I have crashes on both setups work or home.

**Comment by Eyu-Tech** [comment]
Could it be the display driver? This Laptop uses Intel HD graphics (HD 620)

**Comment by Eyu-Tech** [comment]
Issue didn't appear for a while. Apparently one of the updates fixed the issue.

**Comment by othrayte** [comment]
I've been getting what appears to be the same issue (crashing when typing in the description field) for a while now (months). Just happened again with 1.56.1.0. I do note that I am using windows over an RDP session. The DPI scaling is set to 175% but when logged in via RDP it forces everything to 100% so that might be related but I also think I have seen the crash in the passed without the scaling setup this way. So far I have not been able to isolate the issue to just when the DPI scaling is setup this way.

I would also note that when I start fork up again after this issue it usually has lost ~10-20 words of the description, but I don't think it always looses all of it.
